Ensure that Doxygen is called for the generated config file based under the current directory or under the configured top-level source directory. This does not fully fix the problem for a relocated build, but at least the doxygen program finds its request to process (with bad contents so far).
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -264,7 +264,18 @@ man-docs:
 
 ${myDOXDIR}/html:
 if HAVE_DOXYGEN
-	test -d $(top_srcdir)/${myDOXDIR}/html || $(DOXYGEN) $(top_srcdir)/${myDOXDIR}/Doxyfile
+	@ if [ -f ${myDOXDIR}/Doxyfile ]; then \
+		test -d ${myDOXDIR}/html || \
+		$(DOXYGEN) ${myDOXDIR}/Doxyfile; \
+	else \
+		if [ -f $(top_srcdir)/${myDOXDIR}/Doxyfile ]; then \
+			test -d $(top_srcdir)/${myDOXDIR}/html || \
+			$(DOXYGEN) $(top_srcdir)/${myDOXDIR}/Doxyfile; \
+		else \
+			echo "FAIL: No '${myDOXDIR}/Doxyfile' nor '$(top_srcdir)/${myDOXDIR}/Doxyfile' found" >&2; \
+			/bin/false; \
+		fi; \
+	fi
 else
 	@echo "SKIP: Missing 'doxygen' program, sourcecode-documentation generation skipped!" >&2
 endif
