Makefile.am : should not regenerate certain filenames (config.h, Makefile) via .in templates with SED
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -204,14 +204,23 @@ autopathedit = ${SED} \
 	-e 's|@libdir[@]|$(libdir)|g'
 
 define process-in-file =
-	@echo "  SED      $(2)"; rm -f $(2); mkdir -p "`dirname "$(2)"`"; $(autopathedit) < "$(1)" > "$(2)"
+	echo "  SED      $(2)"; rm -f $(2); mkdir -p "`dirname "$(2)"`"; $(autopathedit) < "$(1)" > "$(2)"
 endef
 
 # Catch-all undetailed recipes for .in files to be converted into sources
 # Also used from sub-Makefiles, see docs/examples/Makefile.am for call-syntax
+# Note that some files should not be regenerated by the Makefile via SED when
+# pulled by EXTRA_DIST, so we just verify it exists
 %:: %.in $(abs_top_builddir)/Makefile
-	$(call process-in-file,$<,$@)
-	@for F in $(GENERATEDSCRIPTS) ; do case "$@" in "$$F"|*/"$$F") echo "  CHMOD+X  $@"; chmod +x "$@" || exit $? ;; esac ; done ; true
+	@case "`basename "$@"`" in \
+	    config.h|Makefile) \
+	        if [ -s "$@" ] ; then \
+	            echo "  SKIP-SED $@.in" && exit 0 ; \
+	        else echo "ERROR: Missing file $@ that should have been generated by configure script!" >&2; exit 1; \
+		fi ;; \
+	 esac; \
+	 $(call process-in-file,$<,$@) ; \
+	 for F in $(GENERATEDSCRIPTS) ; do case "$@" in "$$F"|*/"$$F") echo "  CHMOD+X  $@"; chmod +x "$@" || exit $? ;; esac ; done ; true
 
 # Note the public API binary library files are installed to the system
 # common $(libdir), not private $(pkglibdir) like e.g. REST API module
