Fix up packaged malamute service dependencies for bundling with 42ity based products

diff --git a/obs/preinstallimage-bios.sh.in b/obs/preinstallimage-bios.sh.in
--- a/obs/preinstallimage-bios.sh.in
+++ b/obs/preinstallimage-bios.sh.in
@@ -60,6 +60,14 @@ echo "    IMGTYPE='$IMGTYPE'"
 # Protect against errors... such as maybe running on a dev workstation
 set -e
 
+# bashism to get errors from pipelines
+set -o pipefail
+
+die() {
+    echo "FATAL: $*" >&2
+    exit 1
+}
+
 # Setup core dumps
 if true; then
     mkdir -p /var/crash
@@ -495,9 +503,27 @@ ExecStop=/bin/kill -15 \$MAINPID
 PIDFile=/var/run/saslauthd/saslauthd.pid
 
 [Install]
-WantedBy=multi-user.target
+WantedBy=bios-pre-eula.target
 EOF
 /bin/systemctl enable saslauthd
+
+# Change the malamute unit file in-place
+( UNITFILE=/usr/lib/systemd/system/malamute.service
+if ! egrep -q '^PartOf=' "${UNITFILE}" ; then
+    sed -e 's,^\(\[Unit\]\).*$,\1\nPartOf=\n,' \
+        -i "${UNITFILE}" \
+        || exit
+fi
+
+if ! egrep -q '^Before=' "${UNITFILE}" ; then
+    sed -e 's,^\(\[Unit\]\).*$,\1\nBefore=\n,' \
+        -i "${UNITFILE}" \
+        || exit
+fi
+
+sed -e 's,^\(WantedBy\|RequiredBy\|PartOf\|Before\)=\(.*\)$,\1=bios-pre-eula.target,g' \
+    -i "${UNITFILE}"
+) || die "Failed to generate malamute for 42ity service"
 
 mkdir -p /etc/update-rc3.d
 cp /usr/share/fty/examples/config/update-rc3.d/* /etc/update-rc3.d
