BIOS-1234: bios-passwd: forward the error code from testpass.sh
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/tools/bios-passwd.in b/tools/bios-passwd.in
--- a/tools/bios-passwd.in
+++ b/tools/bios-passwd.in
@@ -110,7 +110,7 @@ fi
 
 if [ -x "$TESTPASS" ]; then
     (echo "${USER}"; echo "${NEW_PASSWD}") | "$TESTPASS" || \
-        die "FAILED($?) the password strength test"
+        { RES=$?; echo "FAILED($RES) the password strength test" >&2; exit $RES; }
 else
     die "Can not test password strength: TESTPASS='$TESTPASS' not executable"
 fi
