compress-logs : cosmetic fixes
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/tools/compress-logs b/tools/compress-logs
--- a/tools/compress-logs
+++ b/tools/compress-logs
@@ -73,21 +73,22 @@ find . -type f -name '*.?' | while read F ; do
         continue
     fi
 
-    echo "`date`: Compressing $F: `ls -lad "$F"`" >&2
+    echo "`date`: Compressing $F ...`" >&2
     time $CMDARCH < "$F" > "$F.$EXTARCH.$EXTWIP" && \
     mv -f "$F.$EXTARCH.$EXTWIP" "$F.$EXTARCH" && \
     rm -f "$F"
     RES=$?
 
     if [ "$RES" = 0 ]; then
-        echo "`date`: [--OK--] : Compressing $F: `ls -lad "$F.$EXTARCH"`" >&2
+        echo "`date`: [--OK--] : Compressed $F: `ls -lad "$F.$EXTARCH"`" >&2
         COUNT_OK=$(($COUNT_OK+1))
     else
-        echo "`date`: [-FAIL-] ($RES): Compressing $F: `ls -lad "$F.$EXTARCH"*`" >&2
+        echo "`date`: [-FAIL-] ($RES): Not compressed $F: `ls -lad "$F"*`" >&2
         COUNT_FAIL=$(($COUNT_FAIL+1))
     fi
 done
 
-echo "`date`: $0 Done; compressed $COUNT_OK files; failed to compress $COUNT_FAIL files; did not compress $COUNT_USED files due to being used" >&2
+echo "Compressed $COUNT_OK files; failed to compress $COUNT_FAIL files; did not compress $COUNT_USED files due to being used" >&2
 echo "Old abandoned writes: $COUNT_WIP_KEEP kept as accessed, $COUNT_WIP_WIPE removed and $COUNT_WIP_WIPE_FAIL failed to remove" >&2
+echo "`date`: $0 Done"
 # TOTHINK: Should we fail the service or not, if COUNT_FAIL>0?
