BIOS-2839 : compress-logs : allow to point the script at a specific log directory and basename (still default to /var/log/*)
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/tools/compress-logs b/tools/compress-logs
--- a/tools/compress-logs
+++ b/tools/compress-logs
@@ -28,8 +28,30 @@ LC_ALL=C
 TZ=UTC
 export LANG LC_ALL TZ
 
-# TODO: Should these be settable via service envvars (/etc/default/bios*)?
-LOGDIR="/var/log"
+# By default we compress all not-compressed logs with a single-char suffix
+# LOGFILE_BASENAME (or rather CLI arg #1) allows to do it for just one log
+# file family, e.g. "messages" or "/var/log/commands.log"
+# TODO: Should defaults be settable via service envvars (/etc/default/bios*)?
+LOGFILE_BASENAME="${1-}"
+[ -z "$LOGFILE_BASENAME" ] && LOGFILE_BASENAME='/var/log/*'
+
+LOGDIR="`dirname "$LOGFILE_BASENAME"`" || LOGDIR=""
+[ -n "$LOGDIR" ] && [ x"$LOGDIR" != x"." ] && [ x"$LOGDIR" != x"./" ] || \
+    LOGDIR="/var/log"
+LOGDIR="`cd "$LOGDIR" && pwd`" || exit 1
+
+LOGFILE_BASENAME="`basename "$LOGFILE_BASENAME"`"
+[ -z "$LOGFILE_BASENAME" ] && LOGFILE_BASENAME='*'
+
+# The script does potentially dangerous things at location that can be
+# specified by the caller, so limit its impact
+case "$LOGDIR" in
+    /var/log|/var/log/*|/var/adm|/var/adm/*|/tmp|/tmp/*|/var/tmp|/var/tmp/*|/home/*) ;; # OK
+    *)  echo "ERROR: The log compression should be targeted to a system log directory ('$LOGDIR' is not acceptable)" >&2
+        exit 1
+        ;;
+esac
+
 EXTWIP="__WRITING__"
 EXTARCH="bz2"
 CMDARCH="bzip2 -c -9"
@@ -46,7 +68,7 @@ COUNT_WIP_KEEP=0
 COUNT_WIP_WIPE=0
 COUNT_WIP_WIPE_FAIL=0
 
-find . -type f -name '*.'"$EXTWIP" | while read F ; do
+find . -type f -name "$LOGFILE_BASENAME.$EXTWIP" | while read F ; do
     [ -f "$F" ] && [ -s "$F" ] || continue
 
     echo "`date`: Checking if $F is abandoned: `ls -lad "$F"`" >&2
@@ -64,7 +86,7 @@ find . -type f -name '*.'"$EXTWIP" | while read F ; do
 done
 
 # Assumption: no whitespace in filenames
-for F in `find . -type f -name '*.?'`; do
+for F in `find . -type f -name "$LOGFILE_BASENAME"'.?'`; do
     [ -f "$F" ] && [ -s "$F" ] || continue
 
     echo "`date`: Checking if $F is abandoned: `ls -lad "$F"`" >&2
