db-init(.in) : whitespace and comments revised
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/tools/db-init.in b/tools/db-init.in
--- a/tools/db-init.in
+++ b/tools/db-init.in
@@ -61,7 +61,7 @@ MYCNF="$HOME/.my.cnf"
 # Flag used to set a password, empty if defaults suffice
 MYSQL_ROOT_PASSWD_FLAG=''
 
-# Legacy support
+# Legacy support - we import data and remove this file if present
 [ -s /etc/default/mysql-root-passwd ] && . /etc/default/mysql-root-passwd
 # Can set MYSQL_ROOT_PASSWD value
 
@@ -97,6 +97,7 @@ random_password() {
 }
 
 secure_database() {
+	# Make sure that credentials for R/O and R/W BIOS services are up to date
 	GOOD_BIOS_RW=no
 	GOOD_BIOS_RO=no
 	[ -s /etc/default/bios-db-rw ] && \
@@ -131,6 +132,8 @@ EOF
 	fi
 }
 
+# Common variable fir this run, even if several schema updates are uploaded
+# in different seconds
 SQLINSTALL_TIMESTAMP="t=`date -u '+%Y%m%dT%H%M%SZ'`"
 
 install_sql_file() {
@@ -186,13 +189,13 @@ generate_database() {
 }
 
 upgrade_database() {
-    # Parameters: $1 refers to full filename of new SQL data file
+	# Parameters: $1 refers to full filename of new SQL data file
 	local SQL_FILE="$1"
-    # If there is no parameter, use first initialization sql script
+	# If there is no parameter, use first initialization sql script
 	[ -z "$SQL_FILE" ] && SQL_FILE="$INITSQL_FIRST"
-    # Get file base name without the path
+	# Get file base name without the path
 	local SQL_FILE_BASENAME="`basename "$SQL_FILE"`"
-    # If we got only basename of the file, we will SUPPOSE that it is in the default directory
+	# If we got only basename of the file, we will SUPPOSE that it is in the default directory
 	[ x"$SQL_FILE" = x"$SQL_FILE_BASENAME" ] && SQL_FILE="$INITSQL_DIR/$SQL_FILE_BASENAME"
 
 	if [ -s "${UPGRADE_POLICY_FILE}" ]; then
@@ -207,11 +210,11 @@ upgrade_database() {
 		return 0
 	fi
 
-    # TODO The method may depend on "${UPGRADE_POLICY}" ...
-    install_sql_file "$SQL_FILE" "applying patch '${SQL_FILE}'" || return $?
+	# TODO The method may depend on "${UPGRADE_POLICY}" ...
+	install_sql_file "$SQL_FILE" "applying patch '${SQL_FILE}'" || return $?
 
-    # Currently we prohibit service startup with inconsistent database,
-    # so exit at this point and force a human to take a look at it
+	# Currently we prohibit service startup with inconsistent database,
+	# so exit at this point and force a human to take a look at it
 	if [ "${UPGRADE_POLICY}" = not-required ]; then
 		echo "WARNING: Database upgrade failed, but policy is '$UPGRADE_POLICY' and so we proceed..." >&2
 		return 0
@@ -222,7 +225,7 @@ upgrade_database() {
 
 grep_sql_version() {
 	# Prints e.g. 20151015 from stddin that contains
-    # ASSUMPTION: every sql file SHOULD contain the string according the following TEMPLATE
+	# ASSUMPTION: every sql file SHOULD contain the string according the following TEMPLATE
 	# SET @bios_db_schema_version = '20151015' ;
 	egrep -i '^[ \t]*set[ \t]+@bios_db_schema_version[ \t]*=' | head -1 | \
 	sed -e 's,^.*[ \t]*=[ \t]*\(.*\)[ \t]*;$,\1,' \
@@ -280,63 +283,63 @@ verify_schema_version() {
 	[ x"$SQL_FILE" = x"$SQL_FILE_BASENAME" ] && SQL_FILE="$INITSQL_DIR/$SQL_FILE_BASENAME"
 
 	# Verify that our SQL file has the information about its version
-    # So verify, if this file fulfills the ASSUMPTION
+	# So verify, if this file fulfills the ASSUMPTION
 	local SCHEMA_VERSION_SQL=""
 	if [ -r "$SQL_FILE" ] && [ -s "$SQL_FILE" ] \
 	; then
 		SCHEMA_VERSION_SQL="`grep_sql_version < "$SQL_FILE"`" \
-            || SCHEMA_VERSION_SQL=""
-    fi
+			|| SCHEMA_VERSION_SQL=""
+	fi
 	if [ -z "$SCHEMA_VERSION_SQL" ]; then
 		echo "ERROR: File '$SQL_FILE' is in the inconsistent state, because it doesn't contain the string 'SET @bios_db_schema_version = 'YYYYMMDD' '" >&2
-        # this error should not appear on the customer side, unless someone touch sql files
-        # abort immediately
-        exit 2
-    fi
+		# this error should not appear on the customer side, unless someone touch sql files
+		# abort immediately
+		exit 2
+	fi
 
-    # Select import tags from database
+	# Select import tags from database
 	local SCHEMA_VERSION_DB_1=$(exec_sql_db "SELECT version FROM t_bios_schema_version WHERE tag='begin-import' AND filename='$SQL_FILE_BASENAME' ORDER BY id DESC LIMIT 1;") || \
 		SCHEMA_VERSION_DB_1="begin-NA"
 	local SCHEMA_VERSION_DB_2=$(exec_sql_db "SELECT version FROM t_bios_schema_version WHERE tag='finish-import' AND filename='$SQL_FILE_BASENAME' ORDER BY id DESC LIMIT 1;") || \
 		SCHEMA_VERSION_DB_2="finish-NA"
 
-    # Verify if this database and version information are available
+	# Verify if this database and version information are available
 	if [ x"$SCHEMA_VERSION_DB_1" = x"begin-NA" ] || \
 	   [ x"$SCHEMA_VERSION_DB_2" = x"finish-NA" ] \
 	; then
 		echo "ERROR: 1. Mysql is not running or 2. There are problems with t_bios_schema_version table. Fix them manually" >&2
-        # abort immediately
+		# abort immediately
 		exit 2
-    fi
+	fi
 
-    # Verify if this particular file wasn't imported yet at all
+	# Verify if this particular file wasn't imported yet at all
 	if [ -z "$SCHEMA_VERSION_DB_1" ] && \
 	   [ -z "$SCHEMA_VERSION_DB_2" ] \
 	; then
 		echo "File '$SQL_FILE' wasn't imported yet, import it now"
 		upgrade_database "$SQL_FILE"
 		return $?
-    fi
-
-	# Verify that begin-import and finish-import version tags are the same
-    if [ x"$SCHEMA_VERSION_DB_1" != x"$SCHEMA_VERSION_DB_2" ] || \
-       [ -z "$SCHEMA_VERSION_DB_1" ] || [ -z "$SCHEMA_VERSION_DB_2" ] \
-    ; then
-        echo "Error: Schema version for '$SQL_FILE' is not consistent in the database ('$SCHEMA_VERSION_DB_1' vs '$SCHEMA_VERSION_DB_2'). Investigate and fix it manually" >&2
-        # abort immediately
-        exit 2
 	fi
 
-    # Verify if version of the file is the same as version of the file in the database
+	# Verify that begin-import and finish-import version tags are the same
+	if [ x"$SCHEMA_VERSION_DB_1" != x"$SCHEMA_VERSION_DB_2" ] || \
+	   [ -z "$SCHEMA_VERSION_DB_1" ] || [ -z "$SCHEMA_VERSION_DB_2" ] \
+	; then
+		echo "Error: Schema version for '$SQL_FILE' is not consistent in the database ('$SCHEMA_VERSION_DB_1' vs '$SCHEMA_VERSION_DB_2'). Investigate and fix it manually" >&2
+		# abort immediately
+		exit 2
+	fi
+
+	# Verify if version of the file is the same as version of the file in the database
 	if [ x"$SCHEMA_VERSION_DB_2" != x"$SCHEMA_VERSION_SQL" ]; then
 		echo "Error: Schema version for '$SQL_FILE' in the database is not the same as in current SQL schema file ('$SCHEMA_VERSION_DB_2' vs '$SCHEMA_VERSION_SQL')" >&2
-        echo "NOT IMPLEMENTED"
-        # abort immediately
-        exit 2
+		echo "NOT IMPLEMENTED"
+		# abort immediately
+		exit 2
 	fi
 
 	echo "Schema component '$SQL_FILE' version '$SCHEMA_VERSION_DB_2' is up-to-date"
-    return 0
+	return 0
 }
 
 ensure_root_password || exit $?
@@ -359,7 +362,9 @@ fi
 # e.g. to detect botched imports, need of upgrades, etc. - do it here
 # Here we pick basenames from foth INITSQL_DIR and database, and also
 # make sure to verify INITSQL_FIRST (whether the file exists or not)
-for F in "$INITSQL_FIRST" `{ ls -1 "${INITSQL_DIR}"/*.sql | sed 's,^.*/\([^\/]*$\),\1,'; exec_sql_db 'SELECT DISTINCT filename FROM t_bios_schema_version;' ; }  | sort | uniq | grep -v "$(basename $INITSQL_FIRST)"` ; do
+for F in "$INITSQL_FIRST" \
+	`{ ls -1 "${INITSQL_DIR}"/*.sql | sed 's,^.*/\([^\/]*$\),\1,'; exec_sql_db 'SELECT DISTINCT filename FROM t_bios_schema_version;' ; } | sort | uniq | grep -v "$(basename $INITSQL_FIRST)"` \
+; do
 	verify_schema_version "$F" || exit $?
 done
 
