db-init : echo the fatal errors to stderr
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/tools/db-init.in b/tools/db-init.in
--- a/tools/db-init.in
+++ b/tools/db-init.in
@@ -94,7 +94,7 @@ EOF
 
 		echo "Database for BIOS - completed the schema import and password generation"
 	else
-		echo "Can't read '$INITSQL' !!!"
+		echo "Error: Can't read '$INITSQL' !!!" >&2
 		exit 1
 	fi
 else
