db-init : fall back to empty MYSQL_ROOT_PASSWD if the saved one does not work, just in case this helps (e.g. after rm -rf /var/lib/mysql)
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/tools/db-init.in b/tools/db-init.in
--- a/tools/db-init.in
+++ b/tools/db-init.in
@@ -37,8 +37,13 @@ do_mysql() {
 }
 
 if [ -z "`echo "select 'working';" | do_mysql | grep working`" ]; then
-	echo "Can't connect to database"
-	exit 1
+	if [ -z "`echo "select 'working';" | MYSQL_ROOT_PASSWD='' do_mysql | grep working`" ]; then
+		echo "Can't connect to database"
+		exit 1
+	else
+		echo "Configuration files inconsistent: really MYSQL_ROOT_PASSWD is empty"
+		MYSQL_ROOT_PASSWD=''
+	fi
 fi
 BIOS_RW="`head -c 12 /dev/urandom | base64`"
 BIOS_RO="`head -c 12 /dev/urandom | base64`"
