db-init(.in) : store database credentials under /var (not on /mnt/nand), and move existing valid credentials to new standard locations
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/tools/db-init.in b/tools/db-init.in
--- a/tools/db-init.in
+++ b/tools/db-init.in
@@ -38,6 +38,11 @@ INITSQL_DIR="@datarootdir@/@PACKAGE@/sql/mysql"
 # files from a previous database lifetime, if it is re-initialized.
 # Conversely, as part of /var namespace this is erased during factory-reset.
 INSTSQL_DIR="/var/lib/@PACKAGE@/sql/mysql"
+# This directory also holds the actual database credential files, so they
+# live (and die, in case of factory reset) simultaneously with the database
+# files. The `/root/.my.cnf` and `/etc/default/bios-db-r[ow]` legacy locations
+# are symlinks to actual files in this directory.
+CREDSQL_DIR="$INSTSQL_DIR"
 # This file is applied first; others (if exist in $INITSQL_DIR) will be applied
 # in alphabetic order; all files in $INITSQL_DIR will be version-tested as well
 INITSQL_FIRST="${INITSQL_DIR}/initdb.sql"
@@ -50,10 +55,19 @@ INITSQL_FIRST="${INITSQL_DIR}/initdb.sql"
 
 # This is needed for systemd integration which does not have HOME set
 # The variable is needed not only for ourselves, but also for "mysql" client
+[ -n "$USER" ] || USER="$(id -un)"
+[ $? = 0 ] && [ -n "$USER" ] || USER="root"
 [ -n "$HOME" ] || HOME="$(getent passwd "`id -un`" | awk -F: '{print $6}')"
+# As a fallback, assume "root"
 [ $? = 0 ] && [ -n "$HOME" ] && [ -d "$HOME" ] || HOME="/root"
-export HOME
-MYCNF="$HOME/.my.cnf"
+export HOME USER
+MYCNF_LEGACY="$HOME/.my.cnf"
+MYCNF="$CREDSQL_DIR/.$USER-my.cnf"
+
+BIOS_DB_RO_LEGACY="/etc/default/bios-db-ro"
+BIOS_DB_RO="$CREDSQL_DIR/bios-db-ro"
+BIOS_DB_RW_LEGACY="/etc/default/bios-db-rw"
+BIOS_DB_RW="$CREDSQL_DIR/bios-db-rw"
 
 # MySQL-root password is empty by default, otherwise is cached in $MYCNF
 # and so it is not needed to specify it explicitly either
@@ -98,38 +112,106 @@ random_password() {
 
 secure_database() {
 	# Make sure that credentials for R/O and R/W BIOS services are up to date
+	# Also port legacy files from /etc locations to current store in /var,
+	# leaving only symlinks in the wake, if needed.
 	GOOD_BIOS_RW=no
 	GOOD_BIOS_RO=no
-	[ -s /etc/default/bios-db-rw ] && \
-		( . /etc/default/bios-db-rw && mysql -u "${DB_USER}" --password="${DB_PASSWD}" -D "${DATABASE}" -e "select 'working';" | grep -w working >/dev/null ) && \
+	BIOS_RW_PASS=""
+	BIOS_RO_PASS=""
+	BIOS_RW_USER=""
+	BIOS_RO_USER=""
+
+	if [ -s "${BIOS_DB_RW}" ] ; then
+		BIOS_RW_PASS="`(. "${BIOS_DB_RW}" && echo "${DB_PASSWD}")`" && \
+		BIOS_RW_USER="`(. "${BIOS_DB_RW}" && echo "${DB_USER}")`" && \
+		( mysql -u "${BIOS_RW_USER}" --password="${BIOS_RW_PASS}" -D "${DATABASE}" -e "select 'working';" | grep -w working >/dev/null ) && \
 		GOOD_BIOS_RW=yes
-	[ -s /etc/default/bios-db-ro ] && \
-		( . /etc/default/bios-db-ro && mysql -u "${DB_USER}" --password="${DB_PASSWD}" -D "${DATABASE}" -e "select 'working';" | grep -w working >/dev/null ) && \
+	fi
+	if [ "$GOOD_BIOS_RW" = no ] && [ -s "${BIOS_DB_RW_LEGACY}" ] ; then
+		BIOS_RW_PASS="`(. "${BIOS_DB_RW_LEGACY}" && echo "${DB_PASSWD}")`" && \
+		BIOS_RW_USER="`(. "${BIOS_DB_RW_LEGACY}" && echo "${DB_USER}")`" && \
+		( mysql -u "${BIOS_RW_USER}" --password="${BIOS_RW_PASS}" -D "${DATABASE}" -e "select 'working';" | grep -w working >/dev/null ) && \
+		GOOD_BIOS_RW=yes
+		if [ "$GOOD_BIOS_RW" = yes ]; then
+			echo "Database for BIOS initialization - BIOS_DB_RW_LEGACY pointed to correct password while BIOS_DB_RW did not, rewriting symlink..." >&2 && \
+			rm -f "${BIOS_DB_RW}" && \
+			cat "${BIOS_DB_RW_LEGACY}" > "${BIOS_DB_RW}" && \
+			chown bios "${BIOS_DB_RW}" && \
+			chmod 600 "${BIOS_DB_RW}" && \
+			rm -f "${BIOS_DB_RW_LEGACY}" && \
+			ln -s "${BIOS_DB_RW}" "${BIOS_DB_RW_LEGACY}" \
+			|| { GOOD_BIOS_RW=no; rm -f "${BIOS_DB_RW}" "${BIOS_DB_RW_LEGACY}"; }
+		fi
+	fi
+	[ "$GOOD_BIOS_RW" = no ] && BIOS_RW_PASS="" && BIOS_RW_USER=""
+
+	if [ -s "${BIOS_DB_RO}" ] ; then
+		BIOS_RO_PASS="`(. "${BIOS_DB_RO}" && echo "${DB_PASSWD}")`" && \
+		BIOS_RO_USER="`(. "${BIOS_DB_RO}" && echo "${DB_USER}")`" && \
+		( mysql -u "${BIOS_RO_USER}" --password="${BIOS_RO_PASS}" -D "${DATABASE}" -e "select 'working';" | grep -w working >/dev/null ) && \
 		GOOD_BIOS_RO=yes
+	fi
+	if [ "$GOOD_BIOS_RO" = no ] && [ -s "${BIOS_DB_RO_LEGACY}" ] ; then
+		BIOS_RO_PASS="`(. "${BIOS_DB_RO_LEGACY}" && echo "${DB_PASSWD}")`" && \
+		BIOS_RO_USER="`(. "${BIOS_DB_RO_LEGACY}" && echo "${DB_USER}")`" && \
+		( mysql -u "${BIOS_RO_USER}" --password="${BIOS_RO_PASS}" -D "${DATABASE}" -e "select 'working';" | grep -w working >/dev/null ) && \
+		GOOD_BIOS_RO=yes
+		if [ "$GOOD_BIOS_RO" = yes ]; then
+			echo "Database for BIOS initialization - BIOS_DB_RO_LEGACY pointed to correct password while BIOS_DB_RO did not, rewriting symlink..." >&2 && \
+			rm -f "${BIOS_DB_RO}" && \
+			cat "${BIOS_DB_RO_LEGACY}" > "${BIOS_DB_RO}" && \
+			chown bios "${BIOS_DB_RO}" && \
+			chmod 600 "${BIOS_DB_RO}" && \
+			rm -f "${BIOS_DB_RO_LEGACY}" && \
+			ln -s "${BIOS_DB_RO}" "${BIOS_DB_RO_LEGACY}" \
+			|| { GOOD_BIOS_RO=no; rm -f "${BIOS_DB_RO}" "${BIOS_DB_RO_LEGACY}"; }
+		fi
+	fi
+	[ "$GOOD_BIOS_RO" = no ] && BIOS_RO_PASS="" && BIOS_RO_USER=""
+
 	if [ "$GOOD_BIOS_RW" = no ] || [ "$GOOD_BIOS_RO" = no ]; then
 		echo "Database for BIOS initialization - generating user passwords..."
 
 		[ "$GOOD_BIOS_RW" = yes ] && \
-			BIOS_RW="`(. /etc/default/bios-db-rw && echo "${DB_PASSWD}")`" && \
-			[ -n "$BIOS_RW" ] || BIOS_RW="`random_password`"
+			[ -n "$BIOS_RW_PASS" ] || BIOS_RW_PASS="`random_password`"
+		[ -n "$BIOS_RW_USER" ] || BIOS_RW_USER="bios-rw"
 		[ "$GOOD_BIOS_RO" = yes ] && \
-			BIOS_RO="`(. /etc/default/bios-db-ro && echo "${DB_PASSWD}")`" && \
-			[ -n "$BIOS_RO" ] || BIOS_RO="`random_password`"
+			[ -n "$BIOS_RO_PASS" ] || BIOS_RO_PASS="`random_password`"
+		[ -n "$BIOS_RO_USER" ] || BIOS_RO_USER="bios-ro"
 
 		cat << EOF | do_mysql
-GRANT DELETE,INSERT,SELECT,UPDATE ON ${DATABASE}.* TO 'bios-rw'@'localhost' IDENTIFIED BY '$BIOS_RW';
-GRANT SELECT                      ON ${DATABASE}.* TO 'bios-ro'@'localhost' IDENTIFIED BY '$BIOS_RO';
+GRANT DELETE,INSERT,SELECT,UPDATE ON ${DATABASE}.* TO '$BIOS_RW_USER'@'localhost' IDENTIFIED BY '$BIOS_RW_PASS';
+GRANT SELECT                      ON ${DATABASE}.* TO '$BIOS_RO_USER'@'localhost' IDENTIFIED BY '$BIOS_RO_PASS';
 FLUSH PRIVILEGES;
 EOF
 		[ "$GOOD_BIOS_RW" = yes ] || \
-			printf 'DB_USER="%s"\nDB_PASSWD="%s"\n' "bios-rw" "${BIOS_RW}" > /etc/default/bios-db-rw
+			printf 'DB_USER="%s"\nDB_PASSWD="%s"\n' "${BIOS_RW_USER}" "${BIOS_RW_PASS}" > "${BIOS_DB_RW}"
 		[ "$GOOD_BIOS_RO" = yes ] || \
-			printf 'DB_USER="%s"\nDB_PASSWD="%s"\n' "bios-ro" "${BIOS_RO}" > /etc/default/bios-db-ro
-		chown bios /etc/default/bios-db-r[wo]
-		chmod 600 /etc/default/bios-db-r[wo]
+			printf 'DB_USER="%s"\nDB_PASSWD="%s"\n' "${BIOS_RO_USER}" "${BIOS_RO_PASS}" > "${BIOS_DB_RO}"
+		chown bios "${BIOS_DB_RW}" "${BIOS_DB_RO}"
+		chmod 600 "${BIOS_DB_RW}" "${BIOS_DB_RO}"
 	else
 		echo "Database for BIOS - all existing user passwords are good"
 	fi
+
+	if [ -L "${BIOS_DB_RW_LEGACY}" ] && [ -s "${BIOS_DB_RW}" ] && diff -q "${BIOS_DB_RW_LEGACY}" "${BIOS_DB_RW}" ; then
+		: # Same file in final location, already a symlink in legacy location
+	else
+		# Code above should have ensured that BIOS_DB_RW is correct
+		echo "Database for BIOS initialization - creating BIOS_DB_RW_LEGACY symlink pointing to correct password file BIOS_DB_RW..." >&2 && \
+		rm -f "${BIOS_DB_RW_LEGACY}" && \
+		ln -s "${BIOS_DB_RW}" "${BIOS_DB_RW_LEGACY}"
+	fi
+
+	if [ -L "${BIOS_DB_RO_LEGACY}" ] && [ -s "${BIOS_DB_RO}" ] && diff -q "${BIOS_DB_RO_LEGACY}" "${BIOS_DB_RO}" ; then
+		: # Same file in final location, already a symlink in legacy location
+	else
+		# Code above should have ensured that BIOS_DB_RO is correct
+		echo "Database for BIOS initialization - creating BIOS_DB_RO_LEGACY symlink pointing to correct password file BIOS_DB_RO..." >&2 && \
+		rm -f "${BIOS_DB_RO_LEGACY}" && \
+		ln -s "${BIOS_DB_RO}" "${BIOS_DB_RO_LEGACY}"
+	fi
+
 }
 
 # Common variable fir this run, even if several schema updates are uploaded
@@ -143,20 +225,6 @@ install_sql_file() {
 	# $2 = comment to echo
 	local INITSQL="$1"
 	local COMMENT="$2"
-
-	case "$INSTSQL_DIR" in
-		/*) [ -d "$INSTSQL_DIR" ] || { \
-				echo "Creating INSTSQL_DIR='$INSTSQL_DIR' to save copies of applied SQL files..."; \
-				mkdir -p "$INSTSQL_DIR" && chown bios:root "$INSTSQL_DIR" && chmod 750 "$INSTSQL_DIR"; }
-			[ ! -d "$INSTSQL_DIR" -o ! -w "$INSTSQL_DIR" ] && \
-				echo "WARNING: Can not use INSTSQL_DIR='$INSTSQL_DIR', copies of applied SQL files will not be stashed" >&2 && \
-				INSTSQL_DIR=""
-			;;
-		"") echo "WARNING: Empty INSTSQL_DIR provided, copies of applied SQL files will not be stashed" >&2 ;;
-		*)  echo "ERROR: Non-absolute INSTSQL_DIR='$INSTSQL_DIR' provided, copies of applied SQL files will not be stashed" >&2
-			INSTSQL_DIR=""
-			;;
-	esac
 
 	if  [ -r "$INITSQL" ] && \
 	    [ -s "$INITSQL" ] \
@@ -233,24 +301,58 @@ grep_sql_version() {
 }
 
 ensure_root_password() {
+	if [ -L "${MYCNF_LEGACY}" ] && [ -s "${MYCNF}" ] && diff -q "${MYCNF_LEGACY}" "${MYCNF}" ; then
+		: # Same file in final location, already a symlink in legacy location
+	else
+		if [ -s "${MYCNF_LEGACY}" ] && [ ! -L "${MYCNF_LEGACY}" ] && [ ! -s "${MYCNF}" ]; then
+			# Legacy is a real file, new standard does not exist, move it over
+			echo "Database for BIOS initialization - moving an existing password file MYCNF_LEGACY to MYCNF, and a symlink in its place pointing to the new location..." >&2 && \
+			rm -f "${MYCNF}" && \
+			mv -f "${MYCNF_LEGACY}" "${MYCNF}" && \
+			ln -s "${MYCNF}" "${MYCNF_LEGACY}"
+		fi
+	fi
+
+	# The first attempt uses the $MYCNF_LEGACY file or symlink (in homedir)
+	# The second attempt tries the empty password just in case
+	# Then fall back to try MYCNF if present and different from MYCNF_LEGACY
+	# Then fall back to a very legacy file if present
 	if [ -z "`echo "select 'working';" | do_mysql | grep working`" ]; then
 		if [ -z "`echo "select 'working';" | do_mysql --password='' | grep working`" ]; then
-			if [ -n "$MYSQL_ROOT_PASSWD" ] && [ -n "`echo "select 'working';" | do_mysql --password="$MYSQL_ROOT_PASSWD" | grep working`" ]; then
-				rm -f "$MYCNF"  # Reset access rights, if unsecured earlier
-				printf '[client]\nuser=root\npassword=%s\n' "${MYSQL_ROOT_PASSWD}" > "$MYCNF" && \
-				rm -f /etc/default/mysql-root-passwd
+			if [ -s "$MYCNF" ] && ! diff -q "$MYCNF" "$MYCNF_LEGACY" ]; then
+				# Data in the legacy location was verified to be invalid above
+				rm -f "${MYCNF_LEGACY}" && \
+				ln -s "${MYCNF}" "${MYCNF_LEGACY}"
 				chmod 600 "$MYCNF"
+				if echo "select 'working';" | do_mysql | grep -w working > /dev/null; then
+					echo "Database for BIOS initialization - created a symlink MYCNF_LEGACY pointing to valid password file MYCNF" >&2
+				else # Both data are invalid
+					rm -f "${MYCNF_LEGACY}" "${MYCNF}"
+				fi
+			else # No file(s) or same invalid data
+				rm -f "${MYCNF_LEGACY}" "${MYCNF}"
+			fi
+
+			if [ ! -s "${MYCNF_LEGACY}" ] && [ -n "$MYSQL_ROOT_PASSWD" ] \
+			&& [ -n "`echo "select 'working';" | do_mysql --password="$MYSQL_ROOT_PASSWD" | grep working`" ] \
+			; then
+				rm -f "$MYCNF"  # Reset access rights, if unsecured earlier
+				printf '[client]\nuser=%s\npassword=%s\n' "${USER}" "${MYSQL_ROOT_PASSWD}" > "$MYCNF" && \
+				rm -f /etc/default/mysql-root-passwd # No more legacy
+				chmod 600 "$MYCNF"
+				rm -f "${MYCNF_LEGACY}"
+				ln -s "${MYCNF}" "${MYCNF_LEGACY}"
 			else
 				echo "Error: Can't connect to database" >&2
 				return 1
 			fi
 		else
-			echo "Config files inconsistent: really MYSQL root password is empty (database recreated?)"
+			echo "Config files inconsistent: really MYSQL root password is empty (was database recreated?)" >&2
 			MYSQL_ROOT_PASSWD_FLAG='--password='
 		fi
 	fi
 
-	if [ ! -s "$MYCNF" ] || [ x"$MYSQL_ROOT_PASSWD_FLAG" = x"--password=" ]; then
+	if [ ! -s "$MYCNF" ] || [ ! -s "$MYCNF_LEGACY" ] || [ x"$MYSQL_ROOT_PASSWD_FLAG" = x"--password=" ]; then
 		# ~/.my.cnf missing or empty, or password was detected as empty
 		# Note this structure allows a .my.cnf to specify password=''
 		echo "Database for BIOS - generating MySQL root password instead of corrupt/empty value..."
@@ -263,11 +365,20 @@ EOF
 		[ $? != 0 ] && echo "Error setting MySQL root password" >&2 && return 1
 
 		rm -f "$MYCNF"  # Reset access rights, if unsecured earlier
-		printf '[client]\nuser=root\npassword=%s\n' "${ROOT_PW}" > "$MYCNF"
+		printf '[client]\nuser=%s\npassword=%s\n' "${USER}" "${ROOT_PW}" > "$MYCNF"
 		chmod 600 "$MYCNF"
+		rm -f "${MYCNF_LEGACY}"
+		ln -s "${MYCNF}" "${MYCNF_LEGACY}"
 	else
 		echo "Database for BIOS - not touching MySQL root password - previous value remains in place..."
 	fi
+
+	if [ -z "`echo "select 'working';" | do_mysql | grep working`" ]; then
+		echo "Database for BIOS - final check for MySQL root password failed!" >&2
+		ls -la "${MYCNF}" "${MYCNF_LEGACY}" >&2
+		return 1
+	fi
+
 	return 0
 }
 
@@ -341,6 +452,34 @@ verify_schema_version() {
 	echo "Schema component '$SQL_FILE' version '$SCHEMA_VERSION_DB_2' is up-to-date"
 	return 0
 }
+
+case "$INSTSQL_DIR" in
+	/*) [ -d "$INSTSQL_DIR" ] || { \
+			echo "Creating INSTSQL_DIR='$INSTSQL_DIR' to save copies of applied SQL files..."; \
+			mkdir -p "$INSTSQL_DIR" && chown bios:root "$INSTSQL_DIR" && chmod 750 "$INSTSQL_DIR"; }
+		[ ! -d "$INSTSQL_DIR" -o ! -w "$INSTSQL_DIR" ] && \
+			echo "WARNING: Can not use INSTSQL_DIR='$INSTSQL_DIR', copies of applied SQL files will not be stashed" >&2 && \
+			INSTSQL_DIR=""
+		;;
+	"") echo "WARNING: Empty INSTSQL_DIR provided, copies of applied SQL files will not be stashed" >&2 ;;
+	*)  echo "ERROR: Non-absolute INSTSQL_DIR='$INSTSQL_DIR' provided, copies of applied SQL files will not be stashed" >&2
+		INSTSQL_DIR=""
+		;;
+esac
+
+case "$CREDSQL_DIR" in
+	/*) [ -d "$CREDSQL_DIR" ] || { \
+			echo "Creating CREDSQL_DIR='$CREDSQL_DIR' to save applied database credentials..."; \
+			mkdir -p "$CREDSQL_DIR" && chown bios:root "$CREDSQL_DIR" && chmod 750 "$CREDSQL_DIR"; }
+		;;
+	"") ;;
+	*)  echo "ERROR: Non-absolute CREDSQL_DIR='$CREDSQL_DIR' provided" >&2
+		CREDSQL_DIR=""
+		;;
+esac
+[ -z "$CREDSQL_DIR" ] && [ ! -d "$CREDSQL_DIR" -o ! -w "$CREDSQL_DIR" ] && \
+	echo "WARNING: Can not use CREDSQL_DIR='$CREDSQL_DIR' to save database credentials!" >&2 && \
+	exit 2
 
 ensure_root_password || exit $?
 case "${BIOS_DB_INIT-}" in
