BIOS-1331: db-init : Another error should get to stderr
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/tools/db-init.in b/tools/db-init.in
--- a/tools/db-init.in
+++ b/tools/db-init.in
@@ -110,7 +110,7 @@ grep_sql_version() {
 
 if [ -z "`echo "select 'working';" | do_mysql | grep working`" ]; then
 	if [ -z "`echo "select 'working';" | do_mysql --password='' | grep working`" ]; then
-		echo "Error: Can't connect to database"
+		echo "Error: Can't connect to database" >&2
 		exit 1
 	else
 		echo "Config files inconsistent: really MYSQL root password is empty (database recreated?)"
