tools/db-init.in : added install_sql_file() and refactored generate_database()
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/tools/db-init.in b/tools/db-init.in
--- a/tools/db-init.in
+++ b/tools/db-init.in
@@ -106,39 +106,42 @@ EOF
 		chmod 600 /etc/default/bios-db-r[wo]
 }
 
+SQLINSTALL_TIMESTAMP="t=`date -u '+%Y%m%dT%H%M%SZ'`"
+install_sql_file() {
+	# Currently we allow to install all SQLs at once. But later we can add
+	# a way to install additional schemas in standard manner - this is it.
+	# $1 = SQL pathname
+	# $2 = comment to echo
+	local INITSQL="$1"
+	local COMMENT="$2"
+
+	if  [ -r "$INITSQL" ] && \
+	    [ -s "$INITSQL" ] \
+	; then
+		echo "Database for BIOS initialization - importing $COMMENT `basename $INITSQL`..."
+		do_mysql < "$INITSQL" || return 1
+		SQLINSTALL_SCHEMA_VERSION="v=`grep_sql_version < "$INITSQL"`." || BIOS_SCHEMA_VERSION_SQL=""
+		gzip -c < "$INITSQL" > "$INITSQL.$SQLINSTALL_SCHEMA_VERSION$SQLINSTALL_TIMESTAMP.gz"
+		return 0
+	else
+		echo "Error: Can't read '$INITSQL' !!!" >&2
+		return 1
+	fi
+}
+
 generate_database() {
 	local INITSQL=""
 	# Imports the BIOS database files, sets up and saves passwords
-	TIMESTAMP="t=`date -u '+%Y%m%dT%H%M%SZ'`"
-	if [ -r "$INITSQL_FIRST" ] && \
-	   [ -s "$INITSQL_FIRST" ]; then
-		echo "Database for BIOS initialization - importing base schema..."
-		do_mysql < "$INITSQL_FIRST" || return 1
-		BIOS_SCHEMA_VERSION_SQL="v=`grep_sql_version < "$INITSQL_FIRST"`." || BIOS_SCHEMA_VERSION_SQL=""
-		gzip -c < "$INITSQL_FIRST" > "$INITSQL_FIRST.$BIOS_SCHEMA_VERSION_SQL$TIMESTAMP.gz"
+	install_sql_file "$INITSQL_FIRST" "base schema" || return $?
 
-		secure_database
+	secure_database
 
-		for INITSQL in $(ls -1 "${INITSQL_DIR}"/*.sql | grep -v "`basename $INITSQL_FIRST`" | sort) ; do
-			if  [ -r "$INITSQL" ] && \
-			    [ -s "$INITSQL" ] \
-			; then
-				echo "Database for BIOS initialization - importing extra schema `basename $INITSQL`..."
-				do_mysql < "$INITSQL" || return 1
-				BIOS_SCHEMA_VERSION_SQL="v=`grep_sql_version < "$INITSQL"`." || BIOS_SCHEMA_VERSION_SQL=""
-				gzip -c < "$INITSQL" > "$INITSQL.$BIOS_SCHEMA_VERSION_SQL$TIMESTAMP.gz"
-			else
-				echo "Error: Can't read '$INITSQL' !!!" >&2
-				return 1
-			fi
-		done
+	for INITSQL in $(ls -1 "${INITSQL_DIR}"/*.sql | grep -v "`basename $INITSQL_FIRST`" | sort) ; do
+		install_sql_file "$INITSQL" "extra schema" || return $?
+	done
 
-		echo "Database for BIOS initialization - completed the schema import and password generation"
-		return 0
-	else
-		echo "Error: Can't read '$INITSQL_FIRST' !!!" >&2
-		return 1
-	fi
+	echo "Database for BIOS initialization - completed the schema import and password generation"
+	return 0
 }
 
 upgrade_database() {
