BIOS-592: rc-bios (WIP): use common logmsg_ routines
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/tools/rc-bios b/tools/rc-bios
--- a/tools/rc-bios
+++ b/tools/rc-bios
@@ -38,7 +38,7 @@ DAEMONS_OS_SYSTEMD="malamute nut-client nut-driver nut-monitor mysql saslauthd"
 ### $BIOS-provided daemons (available as systemd units)
 DAEMONS_OUR_SYSTEMD="tntnet@bios bios-agent-inventory bios-db bios-driver-netmon bios-agent-nut bios-server-agent"
 ### Programs which we execute manually
-DAEMONS_OUR_BINS=""
+DAEMONS_OUR_BINS="db-ng agent-nut driver-nmap netmon"
 
 ### List of daemons that we manage as one mega-unit by default
 [ -z "$DAEMONS" ] && \
@@ -62,23 +62,28 @@ echo "INFO: Init-umbrella '$0 $@' will (try to) commence under CHECKOUTDIR='$CHE
 [ -z "$BUILDSUBDIR" -o ! -d "$BUILDSUBDIR" ] && BUILDSUBDIR="$CHECKOUTDIR"
 [ ! -x "$BUILDSUBDIR/config.status" ] && BUILDSUBDIR="$PWD"
 if [ ! -x "$BUILDSUBDIR/config.status" ]; then
-    echo "Cannot find $BUILDSUBDIR/config.status, using system binaries..."
+    echo "Cannot find $BUILDSUBDIR/config.status, using pre-packaged binaries..."
     PATH="/usr/local/bin:/usr/local/lib:/usr/local/libexec:/usr/local/lib/bios:/usr/local/libexec/bios:$PATH"
     PATH="/usr/bin:/usr/lib:/usr/libexec:/usr/lib/bios:/usr/libexec/bios:$PATH"
 else
-    echo "Found $BUILDSUBDIR/config.status, using built binaries preferentially..."
+    echo "Found $BUILDSUBDIR/config.status, using custom-built binaries preferentially..."
     echo "Search path: $PWD, $BUILDSUBDIR, $CHECKOUTDIR, under home, system PATH..."
     PATH="${PWD}:$BUILDSUBDIR:$CHECKOUTDIR:~/bin:~/lib:~/libexec:~/lib/bios:~/libexec/bios:$PATH"
 fi
 export PATH
 
-die() {
+logmsg_die() {
+    [ -z "$CODE" ] || [ "$CODE" -ge 0 ] 2>/dev/null || CODE=1
     echo "FATAL: ${@}" >&2
-    exit 1
+    exit $CODE
 }
 
-warn() {
+logmsg_warn() {
     echo "WARNING: ${@}" >&2
+}
+
+logmsg_info() {
+    echo "INFO: ${@}"
 }
 
 usage() {
@@ -93,6 +98,40 @@ usage() {
     echo "       If no daemons are given, assume all of: $DAEMONS" >&2
     exit 1
 }
+
+update_compiled() {
+    if  [ -z "$CHECKOUTDIR" ] || \
+        [ ! -d "$CHECKOUTDIR" -o ! -x "$CHECKOUTDIR/autogen.sh" ] \
+    ; then
+        # Use system bins, nothing to compile with
+        return 0
+    fi
+
+    if  [ -z "$BUILDSUBDIR" ] || \
+        [ ! -d "$BUILDSUBDIR" -o ! -x "$BUILDSUBDIR/config.status" ] \
+    ; then
+        # Use system bins, nothing to compile
+        return 0
+    fi
+
+    (   cd "$BUILDSUBDIR" || die "Can't use BUILDSUBDIR='$BUILDSUBDIR'"
+        cd "$CHECKOUTDIR" || die "Can't use CHECKOUTDIR='$CHECKOUTDIR'"
+        AUTOGEN_ACTION_CONFIG=config
+        AUTOGEN_ACTION_MAKE=make
+        [ x"$BUILDSUBDIR" != x"$CHECKOUTDIR" ] && \
+            AUTOGEN_ACTION_CONFIG="${AUTOGEN_ACTION_CONFIG}-subdir" && \
+            AUTOGEN_ACTION_MAKE="${AUTOGEN_ACTION_MAKE}-subdir"
+        logmsg_info "Ensuring that the tested programs have been built and up-to-date with CHECKOUTDIR='$CHECKOUTDIR' and BUILDSUBDIR='$BUILDSUBDIR'"
+        if [ ! -f "$BUILDSUBDIR/Makefile" ] ; then
+            ./autogen.sh --nodistclean ${AUTOGEN_ACTION_CONFIG}
+        fi
+        ./autogen.sh --optseqmake ${AUTOGEN_ACTION_MAKE} \
+            web-test-deps $DAEMONS_OUR_BINS
+        exit $? )
+
+    return $?
+}
+
 
 # Simple check for whether sudo is needed for high-privilege tasks
 # We assume here that the non-privileged user running this command
@@ -142,7 +181,7 @@ unit_name() {
     local arg
     arg=${1}
 
-    [ -n "${arg}" ] || die "unit name must not be empty"
+    [ -n "${arg}" ] || logmsg_die "unit name must not be empty"
 
     arg=$(basename "${arg}" .service)
 
@@ -168,7 +207,7 @@ subst_unit() {
     unit=$(unit_name ${1})
 
     [ -n "${unit}" ] || \
-        die "${CHECKOUTDIR}/tools/${unit}.service.in does not exist"
+        logmsg_die "${CHECKOUTDIR}/tools/${unit}.service.in does not exist"
 
     sed -e "s|@libdir[@]/bios|${BUILDSUBDIR}|" \
         -e "s|@libexecdir[@]/bios|${BUILDSUBDIR}|" \
@@ -182,7 +221,7 @@ install_unit_sysd() {
     unit=$(unit_name ${1})
 
     [ -n "${unit}" ] || \
-        die "${CHECKOUTDIR}/tools/${unit}.service.in does not exist"
+        logmsg_die "${CHECKOUTDIR}/tools/${unit}.service.in does not exist"
 
     subst_unit "${unit}" > /tmp/.${unit}.$$.service && \
     $RUNAS mv -f /tmp/.${unit}.$$.service /run/systemd/system/${unit}.service
@@ -194,7 +233,7 @@ get_unit_dependencies() {
     unit=$(unit_name ${1})
 
     [ -n "${unit}" ] || \
-        die "${CHECKOUTDIR}/tools/${unit}.service.in does not exist"
+        logmsg_die "${CHECKOUTDIR}/tools/${unit}.service.in does not exist"
 
     grep '^Requires=' "${CHECKOUTDIR}/tools/${unit}.service.in" | \
         cut -d '=' -f 2 | sed -e 's/.service\>//g' -e 's/[ \t]\+/\n/'
@@ -205,7 +244,7 @@ get_unit_exec() {
     unit=$(unit_name ${1})
 
     [ -n "${unit}" ] || \
-        die "${CHECKOUTDIR}/tools/${unit}.service.in does not exist"
+        logmsg_die "${CHECKOUTDIR}/tools/${unit}.service.in does not exist"
 
     subst_unit "${unit}" | grep -e '^ExecStart=' | cut -d '=' -f 2
 }
@@ -218,12 +257,12 @@ is_daemon_running() {
     [ ! -r "${pidfile}" ] && return 1
     pid=$(head -1 "${pidfile}")
     if [ -z "$pid" -o ! -d "/proc/${pid}" ]; then
-        warn "stale pid file ${pidfile} found, removing"
+        logmsg_warn "stale pid file ${pidfile} found, removing"
         rm -f ${pidfile}
         return 1
     fi
 
-    echo "Service '`basename ${name}`' is already running: PID ${pid}" >&2
+    logmsg_info "Service '`basename ${name}`' is already running: PID ${pid}" >&2
     return 0
 }
 
@@ -237,18 +276,18 @@ start_daemon() {
 
     type "${name}" >/dev/null || \
         [ -x ${name} ] || \
-        die "Can't find executable ${name}"
+        logmsg_die "Can't find executable ${name}"
 
-    warn "START-DAEMON: ${name} ${args}"
+    logmsg_info "START-DAEMON: ${name} ${args}"
     ${name} ${args} &
     pid=$!
-    warn "START-DAEMON: ${name}[${pid}] started"
+    logmsg_info "START-DAEMON: ${name}[${pid}] started"
     echo "${pid}" > "${BUILDSUBDIR}/`basename ${name}`.pid"
 
     # nasty hack to check if pid is still alive - we assume no daemonization
     # will be done by a program! this was script reports success or a fail
     sleep 3
-    warn "START-DAEMON: Testing if PID $pid is still alive..."
+    logmsg_info "START-DAEMON: Testing if PID $pid is still alive..."
     [ -d /proc/${pid} ] && kill -0 ${pid}
 }
 
@@ -272,7 +311,7 @@ stop_daemon() {
 }
 
 run_malamute_user() {
-    [ -x /usr/bin/malamute ] || die "can't find /usr/bin/malamute"
+    [ -x /usr/bin/malamute ] || logmsg_die "can't find /usr/bin/malamute"
 
     start_daemon malamute /etc/malamute/malamute.cfg
 }
@@ -282,16 +321,16 @@ run_unit_user() {
     unit=$(unit_name ${1})
 
     [ -n "${unit}" ] || \
-        die "${CHECKOUTDIR}/tools/${unit}.service.in does not exist"
+        logmsg_die "${CHECKOUTDIR}/tools/${unit}.service.in does not exist"
 
     if [ "${unit}" = "malamute" ]; then
-        run_malamute_user || die "cant run malamute"
+        run_malamute_user || logmsg_die "cant run malamute"
         return 0
     fi
 
     if [ "${unit}" = "mysql" ]; then
         pgrep mysql >/dev/null || \
-            die "starting of mysql is not yet implemented! run it manually"
+            logmsg_die "starting of mysql is not yet implemented! run it manually"
         return 0
     fi
 
@@ -310,10 +349,10 @@ run_unit_sysd() {
     unit=$(unit_name ${1})
 
     [ -n "${unit}" ] || \
-        die "${CHECKOUTDIR}/tools/${unit}.service.in does not exist"
+        logmsg_die "${CHECKOUTDIR}/tools/${unit}.service.in does not exist"
 
     if ! is_external_unit "${unit}"; then
-        install_unit_sysd ${unit} || die "Can't install unit file for ${unit}"
+        install_unit_sysd ${unit} || logmsg_die "Can't install unit file for ${unit}"
     fi
     my_systemctl start ${unit}.service
 }
@@ -326,6 +365,8 @@ can_use_sysd() {
 main() {
 
     [ -n "${1}" ] || usage
+
+    update_compiled
 
     if [ "${1}" = "--kill" ]; then
         if can_use_sysd; then
