tools/start-db-services.in: deb12, start ssh service (port 22)
Signed-off-by: Francois-Regis Degott <FrancoisRegisDegott@eaton.com>

diff --git a/tools/start-db-services.in b/tools/start-db-services.in
--- a/tools/start-db-services.in
+++ b/tools/start-db-services.in
@@ -331,5 +331,11 @@ if [[ -n "$BIOS_DEPS" ]] ; then
     fi
 fi
 
+# finally, start ssh on port 22
+echo "INFO: `date -u`: Activate ssh"
+sudo /bin/systemctl unmask ssh || true
+sudo /bin/systemctl enable ssh || true
+sudo /bin/systemctl start ssh --no-block || echo "WARNING: Failed to start ssh service"
+
 echo "INFO: `date -u`: Done starting IPM Infra services: OK"
 exit 0
