Move /var/lib/fty/license to /var/lib/fty-eula/license and fix FS rights to accomodate new systemd-tmpfiles

diff --git a/tools/start-db-services.in b/tools/start-db-services.in
--- a/tools/start-db-services.in
+++ b/tools/start-db-services.in
@@ -91,7 +91,7 @@ if [[ -f /etc/default/bios-db-rw ]]; then
     exit 0
 fi
 
-[[ -s /var/lib/fty/license ]] || echo "WARNING: the /var/lib/fty/license file is missing or empty" >&2
+[[ -s /var/lib/fty/fty-eula/license ]] || [[ -s /var/lib/fty/license ]] || echo "WARNING: the /var/lib/fty/license file is missing or empty" >&2
 
 # Just in case the service is disabled by preinstall or other means,
 # make it be active (as long as the license acceptance criteria are met).
