Problem: DB is still created during boot
Solution: ... because fty-db-init is pullet via bios-db-init Requires.
Drop fty-db-upgrade (it never made a sense as db-init script do both).
Add fty-db-firstboot, which runs only if db was not initialized and
remains disabled by default. And disable bios-db-init too.

Signed-off-by: Michal Vyskocil <MichalVyskocil@eaton.com>

diff --git a/tools/start-db-services b/tools/start-db-services
--- a/tools/start-db-services
+++ b/tools/start-db-services
@@ -29,7 +29,7 @@ if [[ -f /etc/default/bios-db-rw ]]; then
     exit 0
 fi
 
-sudo /bin/systemctl start fty-db-init || die "Starting fty-db-init failed"
+sudo /bin/systemctl start fty-db-firstboot || die "Starting fty-db-firstboot failed"
 
 sleep 2
 if [[ ! -f /etc/default/bios-db-rw ]]; then
@@ -38,7 +38,6 @@ if [[ ! -f /etc/default/bios-db-rw ]]; then
 fi
 
 sudo /bin/systemctl enable fty-db-init || die "Enabling fty-db-init failed"
-sudo /bin/systemctl enable fty-db-upgrade || die "Enabling fty-db-upgrade failed"
 sudo /bin/systemctl enable mysql || die "Enabling mysql failed"
 
 for DIR in /lib/systemd/system /usr/lib/systemd/system /run/systemd/system /etc/systemd/system/; do
