start-db-services.in : do not restart fty-license-accepted.path either, it is RequiredBy+PartOf fty-license-accepted.target and breaks units that began initializing already

diff --git a/tools/start-db-services.in b/tools/start-db-services.in
--- a/tools/start-db-services.in
+++ b/tools/start-db-services.in
@@ -101,16 +101,16 @@ if [[ "$SYSTEMCTL_COALESCE_INITIAL" = no ]] ; then
     echo "INFO: `date -u`: enable and start fty-license-accepted.path"
     sudo ${SYSTEMCTL} unmask fty-license-accepted.path || die "Unmasking fty-license-accepted.path failed ($?)"
     sudo ${SYSTEMCTL} enable fty-license-accepted.path || die "Enabling fty-license-accepted.path failed ($?)"
-    sudo ${SYSTEMCTL} restart fty-license-accepted.path || die "Restarting fty-license-accepted.path failed ($?)"
+    ### UPDATE: Do not REstart these, to avoid racing on slower systems
+    ### where the normal dependency codepath to start up the units has
+    ### progressed far enough, and only too much later this fallback
+    ### script catches up to "help" and kills the DB mid-initialization.
+    #sudo ${SYSTEMCTL} restart fty-license-accepted.path || die "Restarting fty-license-accepted.path failed ($?)"
     sudo ${SYSTEMCTL} start fty-license-accepted.path || die "Starting fty-license-accepted.path failed ($?)"
 
     echo "INFO: `date -u`: enable and start fty-license-accepted.service"
     sudo ${SYSTEMCTL} unmask fty-license-accepted.service || die "Unmasking fty-license-accepted failed ($?)"
     sudo ${SYSTEMCTL} enable fty-license-accepted.service || die "Enabling fty-license-accepted failed ($?)"
-    ### UPDATE: Do not REstart these, to avoid racing on slower systems
-    ### where the normal dependency codepath to start up the units has
-    ### progressed far enough, and only too much later this fallback
-    ### script catches up to "help" and kills the DB mid-initialization.
     #sudo ${SYSTEMCTL} restart fty-license-accepted.service || die "Restarting fty-license-accepted failed ($?)"
     sudo ${SYSTEMCTL} start fty-license-accepted.service || die "Starting fty-license-accepted failed ($?)"
 
@@ -152,8 +152,8 @@ else
     sudo ${SYSTEMCTL} enable fty-license-accepted.target fty-license-accepted.path fty-license-accepted.service fty-db-engine.service fty-db-init.service fty-db.target \
         || die "Enabling a core database-related service failed ($?)"
 
-    echo "INFO: `date -u`: tickle fty-license-accepted related units"
-    sudo ${SYSTEMCTL} restart fty-license-accepted.path || die "Restarting fty-license-accepted.path failed ($?)"
+    #echo "INFO: `date -u`: tickle fty-license-accepted related units"
+    #sudo ${SYSTEMCTL} restart fty-license-accepted.path || die "Restarting fty-license-accepted.path failed ($?)"
     #sudo ${SYSTEMCTL} restart fty-license-accepted.service || die "Restarting fty-license-accepted failed ($?)"
     #sudo ${SYSTEMCTL} restart fty-license-accepted.target || die "Restarting fty-license-accepted.target failed ($?)"
     #sleep 3
