BIOS-2269 : systemctl : Extend systemctl wrapper to allow simply listing the installed (known) manageable BIOS services that match the filter
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/tools/systemctl b/tools/systemctl
--- a/tools/systemctl
+++ b/tools/systemctl
@@ -266,6 +266,227 @@ $lOTHER"
             done; echo "]"; }
 }
 
+list_known_unit_files() {
+    find {/usr/lib,/lib,/etc,/var/run}/systemd/system /var/run/systemd/generator.late -type f -or -type l
+}
+
+list_known_ipm_unit_files() (
+    # NOTE: This prints pathnames, so there may be several hits per unit, e.g.
+    # with a packaged implementation, local customization and "/etc/...wants"
+    # For mass-matching sed+egrep are more efficient than multiple shell calls
+    # ...by about 45 times over 35 unit matches in test...
+    ###list_known_unit_files | while read F ; do isAllowed_Unit "`basename "$F"`" && echo "$F" ; done
+    SYSTEMCTL_UNITS_REGEX_SINGLE_BY_BASENAME="`echo "$SYSTEMCTL_UNITS_REGEX_SINGLE" | sed 's,^\^,(^|/),'`"
+    list_known_unit_files | egrep "$SYSTEMCTL_UNITS_REGEX_SINGLE_BY_BASENAME"
+)
+
+list_known_ipm_units() {
+    # NOTE: This prints just sorted unique basenames
+    # Piping directly from list_known_unit_files() is just marginally faster
+    list_known_ipm_unit_files | sed 's,^.*/\([^/]*\)$,\1,' | sort | uniq
+}
+
+systemctl_list_ipm_units() (
+    # This routine is our custom feature to speed up field support.
+    # It lists units whose files are installed (or defined, for svc@instances)
+    # locally, and can filter by certain states. It does not pollute the output
+    # with unit names that are NOT INSTALLED.
+    # We support listing of "--missing" units explicitly for non-regex names.
+    LIST_UNITS=""
+    LIST_STATES=""
+    LIST_MISSING="no"
+
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            --ipm-installed|--internal) LIST_UNITS="$LIST_UNITS ORIGIN:INTERNAL" ;;
+            --ipm-deps|--external) LIST_UNITS="$LIST_UNITS ORIGIN:EXTERNAL" ;;
+            --active) LIST_STATES="$LIST_STATES STATE:ACTIVE" ;;
+            --inactive|--not-active) LIST_STATES="$LIST_STATES STATE:INACTIVE" ;;
+            --enabled) LIST_STATES="$LIST_STATES STATE:ENABLED" ;;
+            --disabled|--not-enabled) LIST_STATES="$LIST_STATES STATE:DISABLED" ;;
+            --missing) LIST_MISSING="yes" ;;
+            *) die_ACTION_NOT_ALLOWED ;;
+        esac
+        shift
+    done
+
+    # Mutually exclusive options effectively mean we want everything...
+    # Also note they are alphabetically pre-sorted ;)
+    [[ -n "$LIST_UNITS" ]] && \
+    LIST_UNITS="`for T in $LIST_UNITS ; do echo "$T" ; done | sort | uniq | tr '\n' " "`" && \
+    [[ "$LIST_UNITS" =~ ORIGIN:EXTERNAL.*ORIGIN:INTERNAL ]] && LIST_UNITS=""
+
+    # If caller wants missing units, they have no systemd state to care about
+    [[ x"$LIST_MISSING" = x"yes" ]] && LIST_STATES=""
+    [[ -n "$LIST_STATES" ]] && \
+    LIST_STATES="`for T in $LIST_STATES ; do echo "$T" ; done | sort | uniq | tr '\n' " "`" && \
+    [[ "$LIST_STATES" =~ (STATE:ACTIVE.*STATE:INACTIVE|STATE:DISABLED.*STATE:ENABLED) ]] && LIST_STATES=""
+
+    [[ -z "$LIST_UNITS" ]] && LIST_UNITS="ORIGIN:ANY"
+    [[ -z "$LIST_STATES" ]] && LIST_STATES="STATE:ANY"
+
+    # List of unique unit filenames known to the system that match our filter
+    ALL_KNOWN_UNITS="`list_known_ipm_units`"
+    SYSTEMCTL_UNITS=""
+
+    [[ -n "$ALL_KNOWN_UNITS" ]] && \
+    if [[ "$LIST_UNITS" = "ORIGIN:ANY" ]]; then
+        # Avoid two loops of regex over the same data
+        SYSTEMCTL_UNITS="$ALL_KNOWN_UNITS"
+    else
+        # NOTE/TODO: Potentially support more than these two types later on
+        # NOTE: "egrep" is a bit faster than bash while+regex here, but it
+        # relies on unit entries being one per line
+        SYSTEMCTL_UNITS_INTERNAL=""
+        SYSTEMCTL_UNITS_EXTERNAL=""
+        if [[ "$LIST_UNITS" =~ ORIGIN:INTERNAL ]] > /dev/null ; then
+            #SYSTEMCTL_UNITS_INTERNAL="`echo "$ALL_KNOWN_UNITS" | while read F ; do [[ "$F" =~ $SYSTEMCTL_UNITS_REGEX_SINGLE_INTERNAL ]] > /dev/null && echo "$F"; done`"
+            SYSTEMCTL_UNITS_INTERNAL="`echo "$ALL_KNOWN_UNITS" | egrep "$SYSTEMCTL_UNITS_REGEX_SINGLE_INTERNAL"`"
+        fi
+        if [[ "$LIST_UNITS" =~ ORIGIN:EXTERNAL ]] > /dev/null ; then
+            #SYSTEMCTL_UNITS_EXTERNAL="`echo "$ALL_KNOWN_UNITS" | while read F ; do [[ "$F" =~ $SYSTEMCTL_UNITS_REGEX_SINGLE_EXTERNAL ]] > /dev/null && echo "$F"; done`"
+            SYSTEMCTL_UNITS_EXTERNAL="`echo "$ALL_KNOWN_UNITS" | egrep "$SYSTEMCTL_UNITS_REGEX_SINGLE_EXTERNAL"`"
+        fi
+
+        SYSTEMCTL_UNITS="$SYSTEMCTL_UNITS_INTERNAL"
+        if [[ -n "$SYSTEMCTL_UNITS_EXTERNAL" ]] ; then
+            [[ -z "$SYSTEMCTL_UNITS" ]] \
+                && SYSTEMCTL_UNITS="$SYSTEMCTL_UNITS_EXTERNAL" \
+                || SYSTEMCTL_UNITS="$SYSTEMCTL_UNITS
+$SYSTEMCTL_UNITS_EXTERNAL"
+        fi
+    fi
+
+    if [[ x"$LIST_MISSING" = x"yes" ]] ; then
+        # NOTE: This mode lists something or nothing and exits, always
+        SHOW_UNITS=""
+        if [[ -z "$SYSTEMCTL_UNITS" ]] ; then
+            SHOW_UNITS="`echo "$SYSTEMCTL_UNITS_COMMON $SYSTEMCTL_UNITS_GLOBS" | tr ' ' '\n'`"
+        else
+            for U in $SYSTEMCTL_UNITS_COMMON ; do
+                echo "$SYSTEMCTL_UNITS" | \
+                egrep "^$U"'($|\.(service|timer|target))$' > /dev/null \
+                || SHOW_UNITS="$SHOW_UNITS
+$U"
+            done
+            for U in `echo "$SYSTEMCTL_UNITS_GLOBS" | sed 's,@\*$,,'` ; do
+                echo "$SYSTEMCTL_UNITS" | \
+                egrep "^$U"'@[^[:blank:]]+($|\.(service|timer|target))$' > /dev/null \
+                || SHOW_UNITS="$SHOW_UNITS
+$U"
+            done
+        fi
+
+        [[ -n "$SHOW_UNITS" ]] && echo "$SHOW_UNITS" | egrep -v '^$' && return 0
+
+        echo "No installed units match your selection: $LIST_UNITS STATE:MISSING" | sed 's,  , ,g' >&2
+        return 3
+    fi
+
+    [[ -n "$SYSTEMCTL_UNITS" ]] && \
+    if [ "$LIST_STATES" != "STATE:ANY" ]; then
+        # Logic borrowed from ""--list-json" and simplified since we have all
+        # the unit-naming data pre-filtered already
+        SHOW_UNITS=""
+        SYSTEMCTL_ATTRS="-p Id -p SubState -p ActiveState -p UnitFileState -p LoadState"
+        SYSTEMCTL_INFO="$( vID=""; vSS=""; vLS=""; vAS=""; vUFS=""; \
+        ($SYSTEMCTL show --full $SYSTEMCTL_ATTRS `echo "$SYSTEMCTL_UNITS" | sed 's,\@\.,@.*\\.,g'` && echo "") | \
+        while IFS='=' read -r KEY VALUE; do
+            case "$KEY" in
+                "") if [ -n "$vID" ] ; then
+                        printf '%s\tL:%s\tA:%s\tU:%s\tS:%s\t\n' "$vID" "$vLS" "$vAS" "$vUFS" "$vSS"
+                    fi
+                    vID=""; vSS=""; vLS=""; vAS=""; vUFS=""
+                    ;;
+                Id)
+                    vID="$VALUE";;
+                UnitFileState)
+                    vUFS="$VALUE";;
+                ActiveState)
+                    vAS="$VALUE";;
+                LoadState)
+                    vLS="$VALUE";;
+                SubState)
+                    vSS="$VALUE";;
+                *) # Fallback for different casing, separate to optimize
+                    case "$KEY" in
+                    [Ii][Dd])
+                        vID="$VALUE";;
+                    [Uu][Nn][Ii][Tt][Ff][Ii][Ll][Ss][Tt][Aa][Tt][Ee])
+                        vUFS="$VALUE";;
+                    [Aa][Cc][Tt][Ii][Vv][Ee][Ss][Tt][Aa][Tt][Ee])
+                        vAS="$VALUE";;
+                    [Ll][Oo][Aa][Dd][Ss][Tt][Aa][Tt][Ee])
+                        vLS="$VALUE";;
+                    [Ss][Uu][Bb][Ss][Tt][Aa][Tt][Ee])
+                        vSS="$VALUE";;
+                    esac;;
+            esac
+        done | sort | uniq )" || SYSTEMCTL_INFO=""
+
+        if [ "$DEBUG_SYSTEMCTL" = yes ]; then
+            echo "$SYSTEMCTL_INFO" >&2
+        fi
+
+        [[ -n "$SYSTEMCTL_INFO" ]] && \
+        for U in $SYSTEMCTL_UNITS ; do
+            SHOW_THIS_UNIT=no # Match something below to show up
+            I="`echo "$SYSTEMCTL_INFO" | egrep '^'"$U"`" || I=""
+            if [[ -n "$I" ]]; then
+                ( # Subshell to simplify exit code passing and to limit shopt
+                # TODO: More research into evaluated strings is desirable here
+                shopt -s nocasematch
+                case "$LIST_STATES" in
+                    *STATE:ENABLED*)
+                        case "$I" in
+                            *L:not-loaded*|U:disabled*) SHOW_THIS_UNIT=no ;;
+                            *L:loaded*|U:enabled*|*U:static*|*U:"	"S:*) SHOW_THIS_UNIT=yes ;;
+                            *) SHOW_THIS_UNIT=no ;;
+                        esac
+                        ;;
+                    *STATE:DISABLED*)
+                        case "$I" in
+                            *L:loaded*|U:enabled*|*U:static*|*U:"	"S:*) SHOW_THIS_UNIT=no ;;
+                            *) SHOW_THIS_UNIT=yes ;;
+                        esac
+                        ;;
+                esac
+                case "$LIST_STATES" in
+                    *STATE:ACTIVE*)
+                        case "$I" in
+                            *[AS]:failed*|*A:inactive*|*S:dead*|*S:exited*) SHOW_THIS_UNIT=no ;;
+                            *A:active*|*S:running*|*S:waiting*) SHOW_THIS_UNIT=yes ;;
+                            *) SHOW_THIS_UNIT=no ;;
+                        esac
+                        ;;
+                    *STATE:INACTIVE*)
+                        case "$I" in
+                            *[AS]:failed*|*A:inactive*|*S:dead*|*S:exited*) SHOW_THIS_UNIT=yes ;;
+                            *) SHOW_THIS_UNIT=no ;;
+                        esac
+                        ;;
+                esac
+                [[ "$SHOW_THIS_UNIT" = "yes" ]] # Return this test's exitcode
+                ) && SHOW_THIS_UNIT=yes
+            fi
+            if [[ "$SHOW_THIS_UNIT" = yes ]] ; then
+                if [[ "$DEBUG_SYSTEMCTL" = yes ]] ; then
+                    echo "D: $I" >&2
+                fi
+                [[ -z "$SHOW_UNITS" ]] && SHOW_UNITS="$U" || SHOW_UNITS="$SHOW_UNITS
+$U"
+            fi
+        done
+        SYSTEMCTL_UNITS="$SHOW_UNITS"
+    fi
+
+    [[ -z "$SYSTEMCTL_UNITS" ]] && \
+        echo "No installed units match your selection: $LIST_UNITS $LIST_STATES" | sed 's,  , ,g' >&2 && \
+        return 3
+
+    echo "$SYSTEMCTL_UNITS"
+)
+
 process_CLI_systemctl() {
     # Quick support for specific commands
     case "$1" in
@@ -287,6 +508,11 @@ process_CLI_systemctl() {
         list-json)
             shift
             systemctl_list_json "$@"
+            exit $?
+            ;;
+        list-ipm-units)
+            shift
+            systemctl_list_ipm_units "$@"
             exit $?
             ;;
     esac
