GitIgnore the built tntnet-ExecStartPre.sh and use the path substitutions in the .in script template
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/tools/tntnet-ExecStartPre.sh.in b/tools/tntnet-ExecStartPre.sh.in
--- a/tools/tntnet-ExecStartPre.sh.in
+++ b/tools/tntnet-ExecStartPre.sh.in
@@ -23,17 +23,23 @@
 #  \author Jim Klimov <EvgenyKlimov@Eaton.com>
 #  \brief  Not yet documented file
 
-[ -n "$1" ] || { echo "ERROR: instance name required (suffix after tntnet@ in systemd)" >&2; exit 1; }
+[ -n "$1" ] || { echo "ERROR: instance name required (suffix after tntnet@ in systemd) as the first argument" >&2; exit 1; }
 INST="$1"
 
 echo "Check requirements of tntnet@$INST instance for BIOS"
 
 set -e
-# TODO: Substitute dirname properly via .in parsing
-/usr/share/bios/scripts/ssl-create.sh
-/usr/share/bios/scripts/xml-cat.sh /etc/tntnet/"$INST".d /etc/tntnet/"$INST".xml
+
+echo "Make sure we have an SSL certificate..."
+@datadir@/@PACKAGE@/scripts/ssl-create.sh
+
+echo "Make sure we have a config file..."
+@datadir@/@PACKAGE@/scripts/xml-cat.sh /etc/tntnet/"$INST".d /etc/tntnet/"$INST".xml
 
 F=/etc/default/bios
+echo "Make sure '$F' exists and is properly owned..."
 test -f "${F}" || touch ${F}
 chown www-data: ${F}
 chmod 0644 ${F}
+
+echo "OK"
