update-rc3 : refactor download_rawfwimage_modules() into a wrapper of an updated download_rawfwimage_generic()

diff --git a/tools/update-rc3.in b/tools/update-rc3.in
--- a/tools/update-rc3.in
+++ b/tools/update-rc3.in
@@ -801,7 +801,9 @@ lsdir_http_pattern() {
 download_rawfwimage_generic() (
     # This routine generalizes the download of a firmware image that is
     # checked against a raw partition content (u-Boot and uImage on IPC)
-    # including padding of "empty" tail of allocated partition data.
+    # including padding of "empty" tail of allocated partition data if
+    # a not-empty RAW_DEVICE_NODE is passed, or of a file like modules
+    # archive if the RAW_DEVICE_NODE is empty.
     local CALLER_ROUTINE="$1" ; shift
     local REPORT_IMAGETYPE="$1" ; shift
     local REFER_NEWEST="$1" ; shift
@@ -819,17 +821,17 @@ download_rawfwimage_generic() (
     cd "${DEPLOYMENTROOT_THISIMAGE}" || die "Can not use DOWNLOADROOT_THISIMAGE_VARNAME='$DOWNLOADROOT_THISIMAGE' nor DEPLOYMENTROOT_THISIMAGE_VARNAME='$DEPLOYMENTROOT_THISIMAGE'"
 
     case "${1-}" in
-            *://*)
-                logmsg_info "${CALLER_ROUTINE}() was asked to try downloading '$1' as the raw $REPORT_IMAGETYPE"
-                IMAGE_URL="$1" ;;
-            "")
-                logmsg_info "Fetching newest remote filename for the raw $REPORT_IMAGETYPE..."
-                IMAGE_URL="`${IMAGEFINDER_ROUTINE}`" && [ -n "$IMAGE_URL" ] \
-                && logmsg_info "${CALLER_ROUTINE}() detected '$IMAGE_URL' as the newest remote raw $REPORT_IMAGETYPE" \
-                || { logmsg_error "Could not find any remote raw $REPORT_IMAGETYPE"; IMAGE_URL="";} ;;
-            *)  logmsg_error "${CALLER_ROUTINE}() got an unsupported argument: $*"
-                IMAGE_URL=""
-                ;;
+        *://*)
+            logmsg_info "${CALLER_ROUTINE}() was asked to try downloading '$1' as the ${RAW_DEVICE_NODE:+raw }$REPORT_IMAGETYPE"
+            IMAGE_URL="$1" ;;
+        "")
+            logmsg_info "Fetching newest remote filename for the ${RAW_DEVICE_NODE:+raw }$REPORT_IMAGETYPE..."
+            IMAGE_URL="`${IMAGEFINDER_ROUTINE}`" && [ -n "$IMAGE_URL" ] \
+            && logmsg_info "${CALLER_ROUTINE}() detected '$IMAGE_URL' as the newest remote ${RAW_DEVICE_NODE:+raw }$REPORT_IMAGETYPE" \
+            || { logmsg_error "Could not find any remote ${RAW_DEVICE_NODE:+raw }$REPORT_IMAGETYPE"; IMAGE_URL="";} ;;
+        *)  logmsg_error "${CALLER_ROUTINE}() got an unsupported argument: $*"
+            IMAGE_URL=""
+            ;;
     esac
 
     [ -n "$IMAGE_URL" ] && \
@@ -850,43 +852,67 @@ download_rawfwimage_generic() (
     rIMAGE_CSOLD="${rIMAGE_URL_BASENAME}.${IMAGE_CSALGO}"
     aIMAGE_CSNEW="${TEMP_DATA}/${rIMAGE_URL_BASENAME}.$$.${IMAGE_CSALGO}.tmp"
 
-    IMAGE_CSURL_PADDED="${IMAGE_URL}.${IMAGE_CSALGO}-padded"
-    rIMAGE_CSOLD_PADDED="${rIMAGE_URL_BASENAME}.${IMAGE_CSALGO}-padded"
-    aIMAGE_CSNEW_PADDED="${TEMP_DATA}/${rIMAGE_URL_BASENAME}.$$.${IMAGE_CSALGO}-padded.tmp"
-
-    trap 'TRAPCODE=$?; rm -f "${aIMAGE_CSNEW}" "${aIMAGE_CSNEW_PADDED}"; exit $TRAPCODE' 0
+    if [ -n "${RAW_DEVICE_NODE-}" ]; then
+        IMAGE_CSURL_PADDED="${IMAGE_URL}.${IMAGE_CSALGO}-padded"
+        rIMAGE_CSOLD_PADDED="${rIMAGE_URL_BASENAME}.${IMAGE_CSALGO}-padded"
+        aIMAGE_CSNEW_PADDED="${TEMP_DATA}/${rIMAGE_URL_BASENAME}.$$.${IMAGE_CSALGO}-padded.tmp"
+        trap 'TRAPCODE=$?; rm -f "${aIMAGE_CSNEW}" "${aIMAGE_CSNEW_PADDED}"; exit $TRAPCODE' 0
+    else
+        IMAGE_CSURL_PADDED=''
+        rIMAGE_CSOLD_PADDED=''
+        aIMAGE_CSNEW_PADDED=''
+        trap 'TRAPCODE=$?; rm -f "${aIMAGE_CSNEW}"; exit $TRAPCODE' 0
+    fi
 
     logmsg_info "Downloading '${IMAGE_CSURL}' (if any) into '${aIMAGE_CSNEW}'..."
     fetch_file "${IMAGE_CSURL}" "${aIMAGE_CSNEW}" || true
 
-    logmsg_info "Downloading '${IMAGE_CSURL_PADDED}' (if any) into '${aIMAGE_CSNEW_PADDED}'..."
-    fetch_file "${IMAGE_CSURL_PADDED}" "${aIMAGE_CSNEW_PADDED}" || true
+    if [ -n "${RAW_DEVICE_NODE-}" ]; then
+        logmsg_info "Downloading '${IMAGE_CSURL_PADDED}' (if any) into '${aIMAGE_CSNEW_PADDED}'..."
+        fetch_file "${IMAGE_CSURL_PADDED}" "${aIMAGE_CSNEW_PADDED}" || true
+    fi
 
     # Try the filenames in local directories
     logmsg_info "Verifying if we have this checksum and corresponding file under original name in base dir..."
     verify_threeway_checksum "${IMAGE_URL}" "${rIMAGE_URL_BASENAME}" "${rIMAGE_CSOLD}" "${aIMAGE_CSNEW}" \
         && { echo "`pwd`/${rIMAGE_URL_BASENAME}" > "${REFER_NEWEST}" ;
              return 0 ; }
-    if [ -s "${aIMAGE_CSNEW_PADDED}" ] && [ -c "${RAW_DEVICE_NODE}" ]; then
-        logmsg_info "Verify padded checksum against a raw $REPORT_IMAGETYPE partition with flashed bits here ..."
-        REPLACE_MISSING_CHECKSUM="no" FLAG_CAN_REMOVE_IMAGES="no" verify_threeway_checksum "${IMAGE_URL}" \
-            "${RAW_DEVICE_NODE}" \
-            "${DEPLOYMENTROOT_THISIMAGE}/${rIMAGE_CSOLD_PADDED}" \
-            "${aIMAGE_CSNEW_PADDED}" \
-        && { echo "${RAW_DEVICE_NODE}" > "${REFER_NEWEST}" ;
-             return 0 ; }
+
+    if [ -d "${DEPLOYMENTROOT_THISIMAGE}" ] ; then
+        if [ -n "{RAW_DEVICE_NODE-}" ]; then
+            if [ -s "${aIMAGE_CSNEW_PADDED}" ] && [ -c "${RAW_DEVICE_NODE}" ]; then
+                logmsg_info "Verify padded checksum against a raw $REPORT_IMAGETYPE partition with flashed bits here ..."
+                REPLACE_MISSING_CHECKSUM="no" FLAG_CAN_REMOVE_IMAGES="no" verify_threeway_checksum "${IMAGE_URL}" \
+                    "${RAW_DEVICE_NODE}" \
+                    "${DEPLOYMENTROOT_THISIMAGE}/${rIMAGE_CSOLD_PADDED}" \
+                    "${aIMAGE_CSNEW_PADDED}" \
+                && { echo "${RAW_DEVICE_NODE}" > "${REFER_NEWEST}" ;
+                     return 0 ; }
+            fi
+
+            logmsg_info "Verify non-padded checksum against a raw $REPORT_IMAGETYPE partition with flashed bits here ..."
+            REPLACE_MISSING_CHECKSUM="no" \
+            FLAG_CAN_REMOVE_IMAGES="no" verify_threeway_checksum "${IMAGE_URL}" \
+                    "${RAW_DEVICE_NODE}" \
+                    "${DEPLOYMENTROOT_THISIMAGE}/${rIMAGE_CSOLD}" \
+                    "${aIMAGE_CSNEW}" \
+                && { echo "${RAW_DEVICE_NODE}" > "${REFER_NEWEST}" ;
+                     return 0 ; }
+            logmsg_warn "TODO: If we can detect the file size of the remote image, use calculate_stream_checksum_bytes() to verify flashed bits"
+        else # Not raw device node
+            # Do not remove deployed files!
+            logmsg_info "Verifying if we have this checksum and corresponding file already deployed..."
+            FLAG_CAN_REMOVE_IMAGES="no" verify_threeway_checksum "${IMAGE_URL}" \
+                "${DEPLOYMENTROOT_THISIMAGE}/${rIMAGE_URL_BASENAME}" \
+                "${DEPLOYMENTROOT_THISIMAGE}/${rIMAGE_CSOLD}" \
+                "${aIMAGE_CSNEW}" \
+            && { echo "${DEPLOYMENTROOT_THISIMAGE}/${rIMAGE_URL_BASENAME}" > "${REFER_NEWEST}" ;
+                 return 0 ; }
+        fi
     fi
-    logmsg_info "Verify non-padded checksum against a raw $REPORT_IMAGETYPE partition with flashed bits here ..."
-    REPLACE_MISSING_CHECKSUM="no" FLAG_CAN_REMOVE_IMAGES="no" verify_threeway_checksum "${IMAGE_URL}" \
-            "${RAW_DEVICE_NODE}" \
-            "${DEPLOYMENTROOT_THISIMAGE}/${rIMAGE_CSOLD}" \
-            "${aIMAGE_CSNEW}" \
-        && { echo "${RAW_DEVICE_NODE}" > "${REFER_NEWEST}" ;
-             return 0 ; }
-    logmsg_warn "TODO: If we can detect the file size of the remote image, use calculate_stream_checksum_bytes() to verify flashed bits"
 
     if [ x"${CHECK_ONLY-}" = xyes ]; then
-        logmsg_info "According to checksums, the remote resource '$IMAGE_URL' points to an $REPORT_IMAGETYPE we do not have on this system"
+        logmsg_info "According to checksums, the remote resource '$IMAGE_URL' points to a $REPORT_IMAGETYPE we do not have on this system"
         return 42
     fi
 
@@ -894,14 +920,16 @@ download_rawfwimage_generic() (
     # than what we already have; the aTGT_FILE names the ultimate local filename
     aTGT_FILE="`pwd`/${rIMAGE_URL_BASENAME}"
     aIMAGE_CSOLD="`pwd`/${rIMAGE_CSOLD}"
-    aIMAGE_CSOLD_PADDED="`pwd`/${rIMAGE_CSOLD_PADDED}"
 
     if [ ! -s "${aIMAGE_CSOLD}" ]; then
         [ -s "${aIMAGE_CSNEW}" ] && cp -f "${aIMAGE_CSNEW}" "${aIMAGE_CSOLD}"
     fi
 
-    if [ ! -s "${aIMAGE_CSOLD_PADDED}" ]; then
-        [ -s "${aIMAGE_CSNEW_PADDED}" ] && cp -f "${aIMAGE_CSNEW_PADDED}" "${aIMAGE_CSOLD_PADDED}"
+    if [ -n "${RAW_DEVICE_NODE-}" ]; then
+        aIMAGE_CSOLD_PADDED="`pwd`/${rIMAGE_CSOLD_PADDED}"
+        if [ ! -s "${aIMAGE_CSOLD_PADDED}" ]; then
+            [ -s "${aIMAGE_CSNEW_PADDED}" ] && cp -f "${aIMAGE_CSNEW_PADDED}" "${aIMAGE_CSOLD_PADDED}"
+        fi
     fi
 
     logmsg_info "Downloading '$IMAGE_URL' into '$aTGT_FILE'..."
@@ -909,8 +937,14 @@ download_rawfwimage_generic() (
         { remove_image "$aTGT_FILE"; die "Could not download '$IMAGE_URL' into '$aTGT_FILE'"; }
     remove_checksum_cache '[^\:]*' '[^\:]*' "${aTGT_FILE}"
 
+    if [ -n "${RAW_DEVICE_NODE-}" ]; then
+        HELPER_PATTERN="^(${IMAGE_CSURL}|${IMAGE_CSURL_PADDED})"'$'
+    else
+        HELPER_PATTERN="^${IMAGE_CSURL}"'$'
+    fi
+
     lsdir_http_pattern "${SOURCESITEROOT_THISIMAGE}" "`basename ${IMAGE_URL}`"'*' | egrep "^${IMAGE_URL}\." | \
-        egrep -v "^(${IMAGE_CSURL}|${IMAGE_CSURL_PADDED})"'$' | \
+        egrep -v "${HELPER_PATTERN}" | \
         while read U ; do
             # Note these are helper files, e.g. a padded checksum or some
             # touched-flags (may even be empty) and not fatal if missing
@@ -1407,119 +1441,15 @@ findnewest_rawfwimage_modules() (
 )
 
 download_rawfwimage_modules() (
-    local REPORT_IMAGETYPE='kernel modules archive'
-    REFER_NEWEST="${TEMP_DATA}/.newest-modules"
-    rm -f "${REFER_NEWEST}"
-
-    cd "${DOWNLOADROOTFW_MODULES}" || \
-    cd "${DEPLOYMENTROOTFW_MODULES}" || die "Can not use DOWNLOADROOTFW_MODULES='$DOWNLOADROOTFW_MODULES' nor DEPLOYMENTROOTFW_MODULES='$DEPLOYMENTROOTFW_MODULES'"
-
-    case "${1-}" in
-        *://*)
-            logmsg_info "download_rawfwimage_modules() was asked to try downloading '$1' as the raw $REPORT_IMAGETYPE"
-            IMAGE_URL="$1" ;;
-        "")
-            logmsg_info "Fetching newest remote filename for the raw $REPORT_IMAGETYPE..."
-            IMAGE_URL="`findnewest_rawfwimage_modules`" && [ -n "$IMAGE_URL" ] \
-            && logmsg_info "download_rawfwimage_modules() detected '$IMAGE_URL' as the newest remote raw $REPORT_IMAGETYPE" \
-            || { logmsg_error "Could not find any remote raw $REPORT_IMAGETYPE"; IMAGE_URL="";} ;;
-        *)  logmsg_error "download_rawfwimage_modules() got an unsupported argument: $*"
-            IMAGE_URL=""
-            ;;
-    esac
-
-    [ -n "$IMAGE_URL" ] && \
-    rIMAGE_URL_BASENAME="`basename "$IMAGE_URL"`" && \
-        [ -n "$rIMAGE_URL_BASENAME" ] || \
-        die "Can not find the remote image URL"
-
-    # TODO: Currently hardcoded for md5 accompanying checksums only
-    # TODO (later): Support presence of multiple checksum files (e.g. sha* and md5)
-    # TODO: Also support checksum-verifying against the flashed partition bits
-    IMAGE_CSALGO="${CHECKSUM_ALGO_DEFAULT}"
-
-    # NOTE: "Old" filename and checksum are basenames that can be located under
-    # different directories ("r"elative varnames), but e.g. a "new" checksum is
-    # ensured to be in a temporary location and a newly downloaded file should
-    # land into the recovery location ("a"bsolute varnames)
-    IMAGE_CSURL="${IMAGE_URL}.${IMAGE_CSALGO}"
-    rIMAGE_CSOLD="${rIMAGE_URL_BASENAME}.${IMAGE_CSALGO}"
-    aIMAGE_CSNEW="${TEMP_DATA}/${rIMAGE_URL_BASENAME}.$$.${IMAGE_CSALGO}.tmp"
-
-    trap 'TRAPCODE=$?; rm -f "$aIMAGE_CSNEW"; exit $TRAPCODE' 0
-
-    logmsg_info "Downloading '${IMAGE_CSURL}' (if any) into '${aIMAGE_CSNEW}'..."
-    fetch_file "${IMAGE_CSURL}" "${aIMAGE_CSNEW}" || true
-
-    # Try the filenames in local directories
-    logmsg_info "Verifying if we have this checksum and corresponding file under original name in base dir..."
-    verify_threeway_checksum "${IMAGE_URL}" "${rIMAGE_URL_BASENAME}" "${rIMAGE_CSOLD}" "${aIMAGE_CSNEW}" \
-        && { echo "`pwd`/${rIMAGE_URL_BASENAME}" > "${REFER_NEWEST}" ;
-             return 0 ; }
-
-    if [ -d "${DEPLOYMENTROOT_MODULES}" ] ; then
-        # Do not remove deployed files!
-        logmsg_info "Verifying if we have this checksum and corresponding file already deployed..."
-        FLAG_CAN_REMOVE_IMAGES="no" verify_threeway_checksum "${IMAGE_URL}" \
-            "${DEPLOYMENTROOT_MODULES}/${rIMAGE_URL_BASENAME}" \
-            "${DEPLOYMENTROOT_MODULES}/${rIMAGE_CSOLD}" \
-            "${aIMAGE_CSNEW}" \
-        && { echo "${DEPLOYMENTROOT_MODULES}/${rIMAGE_URL_BASENAME}" > "${REFER_NEWEST}" ;
-             return 0 ; }
-    fi
-
-    if [ x"${CHECK_ONLY-}" = xyes ]; then
-        logmsg_info "According to checksums, the remote resource '$IMAGE_URL' points to a $REPORT_IMAGETYPE we do not have on this system"
-        return 42
-    fi
-
-    # If we are here, the IMAGE_URL is valid and points to a different content
-    # than what we already have; the aTGT_FILE names the ultimate local filename
-    aTGT_FILE="`pwd`/${rIMAGE_URL_BASENAME}"
-    aIMAGE_CSOLD="`pwd`/${rIMAGE_CSOLD}"
-
-    if [ ! -s "${aIMAGE_CSOLD}" ]; then
-        [ -s "${aIMAGE_CSNEW}" ] && cp -f "${aIMAGE_CSNEW}" "${aIMAGE_CSOLD}"
-    fi
-
-    logmsg_info "Downloading '$IMAGE_URL' into '$aTGT_FILE'..."
-    FETCH_VERBOSE=yes fetch_file "$IMAGE_URL" "${aTGT_FILE}" || \
-        { remove_image "$aTGT_FILE"; die "Could not download '$IMAGE_URL' into '$aTGT_FILE'"; }
-    remove_checksum_cache '[^\:]*' '[^\:]*' "${aTGT_FILE}"
-
-    lsdir_http_pattern "${SOURCESITEROOTFW_MODULES}" "`basename ${IMAGE_URL}`"'*' | egrep "^${IMAGE_URL}\." | \
-        egrep -v "^${IMAGE_CSURL}"'$' | \
-        while read U ; do
-            # Note these are helper files, e.g. a padded checksum or some
-            # touched-flags (may even be empty) and not fatal if missing
-            aBU="`pwd`/`basename "$U"`"
-            logmsg_info "Downloading optional additional file '$U' into '$aBU'..."
-            MAYBE_EMPTY fetch_file "${U}" "${aBU}" || true
-        done
-
-    if [ -s "${aIMAGE_CSOLD}" ] || [ -s "${aIMAGE_CSNEW}" ] || [ -s "${DEPLOYMENTROOTFW_MODULES}/${rIMAGE_CSOLD}" ]; then
-        FLAG_CAN_REMOVE_IMAGES="no" verify_threeway_checksum "${IMAGE_URL}" \
-            "${aTGT_FILE}" \
-            "${aIMAGE_CSOLD}" \
-            "${DEPLOYMENTROOTFW_MODULES}/${rIMAGE_CSOLD}" || \
-        verify_threeway_checksum "${IMAGE_URL}" \
-            "${aTGT_FILE}" \
-            "${aIMAGE_CSOLD}" \
-            "${aIMAGE_CSNEW}" || return $?
-    else
-        logmsg_warn "Generating '${aIMAGE_CSOLD}' because there was none at the source..."
-        echo "`calculate_stream_checksum "${IMAGE_CSALGO}" < "$aTGT_FILE"`  `basename "$aTGT_FILE"`" > "${aIMAGE_CSOLD}" || \
-        { rm -f "${aIMAGE_CSOLD}"; die "Could not generate '${aIMAGE_CSOLD}'"; }
-    fi
-
-    # TODO: Verify file size against partition size (flashability after reboot)
-    [ -s "${aTGT_FILE}" ] && [ -s "${aIMAGE_CSOLD}" ] && \
-    touch -r "${aTGT_FILE}" "${aIMAGE_CSOLD}" && \
-    logmsg_info "Got $REPORT_IMAGETYPE OK:" && \
-    ls -ld "${aTGT_FILE}" "${aIMAGE_CSOLD}" && \
-    cat "${aIMAGE_CSOLD}" && \
-    { echo "${aTGT_FILE}" > "${REFER_NEWEST}" ;
-      return 42 ; }
+    download_rawfwimage_generic \
+        'download_rawfwimage_modules' \
+        'kernel modules archive' \
+        "${TEMP_DATA}/.newest-modules" \
+        "DOWNLOADROOTFW_MODULES" "${DOWNLOADROOTFW_MODULES}" \
+        "DEPLOYMENTROOTFW_MODULES" "${DEPLOYMENTROOTFW_MODULES}" \
+        "${SOURCESITEROOTFW_MODULES}" \
+        'findnewest_rawfwimage_modules' \
+        ""
 )
 
 removeold_rawfwimage_modules() (
