update-rc3 : another way to check on available remote resources
Signed-off-by: Jim Klimov <jim@jimklimov.com>

diff --git a/tools/update-rc3 b/tools/update-rc3
--- a/tools/update-rc3
+++ b/tools/update-rc3
@@ -150,6 +150,9 @@ usage() {
     echo "  --help | -help | -h       Display this hep and exit"
     echo "  --config | -c             Source an additional config file (beside looking in"
     echo "                            standard locations e.g. '/etc/update-rc3.d/*.conf')"
+    echo "  -ls              List remote images (except standard checksum files) and do an"
+    echo "                   estimate if the newest differ from local copies. Effect and"
+    echo "                   exitcodes similar to --check* below but with different output."
     echo "  --(no-)check-image-os, --(no-)check-image-fw, --(no-)check-images"
     echo "                   Only check the source location if new images are available"
     echo "                   and exit, whatever the outcome (returns 0 if nothing found,"
@@ -1365,6 +1368,44 @@ while [ $# -gt 0 ]; do
                         logmsg_info "Sourcing configuration file: '$2' ..." && \
                         . "$2" || die "Possibly got an error sourcing '$2', see above..."
                     shift ;;
+		-ls)
+			RES=0
+			lsdir_http_pattern "${SOURCESITEROOTFW_UBOOT}" "uBoot*" \
+				| egrep -v '\.(md5'"$CHECKSUM_ALGO_DEFAULT:+|$CHECKSUM_ALGO_DEFAULT"')$' || RES=$?
+			lsdir_http_pattern "${SOURCESITEROOTFW_UBOOT}" "u-Boot*" \
+				| egrep -v '\.(md5'"$CHECKSUM_ALGO_DEFAULT:+|$CHECKSUM_ALGO_DEFAULT"')$' || RES=$?
+			lsdir_http_pattern "${SOURCESITEROOTFW_UIMAGE}" "uImage*" \
+				| egrep -v '\.(md5'"$CHECKSUM_ALGO_DEFAULT:+|$CHECKSUM_ALGO_DEFAULT"')$' || RES=$?
+			lsdir_http_pattern "${SOURCESITEROOTFW_MODULES}" "*[0-9].[0-9]*.${EXT}*" \
+				| egrep -v '\.(md5'"$CHECKSUM_ALGO_DEFAULT:+|$CHECKSUM_ALGO_DEFAULT"')$' || RES=$?
+			lsdir_http_pattern "${SOURCESITEROOT_OSIMAGE}" "${SOURCESITEROOT_OSIMAGE_FILENAMEPATTERN}.${EXT}*" \
+				| egrep -v '\.(md5'"$CHECKSUM_ALGO_DEFAULT:+|$CHECKSUM_ALGO_DEFAULT"')$' || RES=$?
+
+			summarize_check() {
+				IMG="$1"
+				shift
+				OUT="`CHECK_ONLY=yes "$@" 2>&1`"
+				sRES=$?
+				case "$sRES" in
+					0) echo "$IMG: Local is up-to-date" ;;
+					42) echo "$IMG: Newest remote is different";;
+					*) echo "$IMG: Some error ($sRES):"; echo "$OUT";;
+				esac
+				return $sRES
+			}
+
+			summarize_check "OSIMAGE" download_osimage $URL_DOWNLOAD_OSIMAGE &
+			PID1=$!
+			summarize_check "KERNEL-UIMAGE"  download_rawfwimage_uimage  $URL_DOWNLOAD_FWIMAGE_RAW_UIMAGE &
+			PID2=$!
+			summarize_check "KERNEL-MODULES" download_rawfwimage_modules $URL_DOWNLOAD_FWIMAGE_RAW_MODULES &
+			PID3=$!
+			summarize_check "LOADER-UBOOT"   download_rawfwimage_uboot   $URL_DOWNLOAD_FWIMAGE_RAW_UBOOT &
+			PID4=$!
+			for P in $PID1 $PID2 $PID3 $PID4 ; do wait $P || RES=$? ; done
+			wait || RES=$?
+			exit $RES
+			;;
                 --remove-files)         FLAG_CAN_REMOVE_IMAGES="yes";;
                 --no-remove-files)      FLAG_CAN_REMOVE_IMAGES="no";;
                 --flatten-filenames)    FLAG_FLATTEN_FILENAMES="yes";;
