verify-fs.in : count how many inspections were failed or skipped, summarize in the end to both channels (stderr+logger)

diff --git a/tools/verify-fs.in b/tools/verify-fs.in
--- a/tools/verify-fs.in
+++ b/tools/verify-fs.in
@@ -101,6 +101,9 @@ fi
 [[ -d ${IMAGES} ]] || \
     die "Can't find images ${IMAGES}"
 
+PROBLEMCOUNT=0
+MISSINGCOUNT=0
+
 ## 1.) Verify the images
 pushd "${IMAGES}" >/dev/null
 for ROOTFS in *.squashfs; do
@@ -110,9 +113,11 @@ for ROOTFS in *.squashfs; do
             log "Good integrity of ${ROOTFS}, MD5 checksum is valid"
         else
             log "Bad integrity of ${ROOTFS}, MD5 checksum is not valid"
+            PROBLEMCOUNT=$(($PROBLEMCOUNT+1))
         fi
     else
         log "Missing MD5 checksum file: '${ROOTFS}.md5'"
+        MISSINGCOUNT=$(($MISSINGCOUNT+1))
     fi
 
     if [ -s "${ROOTFS}.sha256" ] ; then
@@ -129,21 +134,27 @@ for ROOTFS in *.squashfs; do
                             log "Image signature is valid for ${ROOTFS}"
                         else
                             log "Image signature is invalid for ${ROOTFS}"
+                            PROBLEMCOUNT=$(($PROBLEMCOUNT+1))
                         fi
                     else
                         log "Manifest signature not found for ${ROOTFS}"
+                        MISSINGCOUNT=$(($MISSINGCOUNT+1))
                     fi
                 else
                     log "Manifest sha256 hash does not match with the sha256 hash for ${ROOTFS}"
+                    PROBLEMCOUNT=$(($PROBLEMCOUNT+1))
                 fi
             else
                 log "Manifest not found for ${ROOTFS}"
+                MISSINGCOUNT=$(($MISSINGCOUNT+1))
             fi
         else
             log "Bad integrity of ${ROOTFS}, SHA256 checksum is not valid"
+            PROBLEMCOUNT=$(($PROBLEMCOUNT+1))
         fi
     else
         log "Missing SHA256 checksum file: '${ROOTFS}.sha256'"
+        MISSINGCOUNT=$(($MISSINGCOUNT+1))
     fi
 
 done
@@ -157,5 +168,12 @@ cat_default | while read LINE; do
     [[ -d "${OVERLAY}/${TREE}" ]] || continue
 
     is_tree_empty "${OVERLAY}/${TREE}" ${EXCLUDES//:/ } || \
-        log "${OVERLAY}/${TREE} contains suspicious files."
+        { log "${OVERLAY}/${TREE} contains suspicious files." ; PROBLEMCOUNT=$(($PROBLEMCOUNT+1)); }
 done
+
+if [ "$PROBLEMCOUNT" = 0 ] ; then
+    logboth "SUCCESS: Completed verify-fs at `date -u` with no problems to report (and $MISSINGCOUNT inspected sources were missing)"
+else
+    logboth "FAILED: Completed verify-fs at `date -u` with $PROBLEMCOUNT problems to report (and $MISSINGCOUNT inspected sources were missing)"
+#    exit 1
+fi
